"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Check } from "lucide-react";
import { Brand, Footer, plans, query, selection } from "../onboarding/components";

export const dynamic = "force-dynamic";

export default function SelectPlan() { const params = useSearchParams(); const chosen = selection(params); const cadence = chosen.cadence; return <div className="onboarding-page"><header className="onboarding-header"><Brand /><span className="header-action">Already have an account? <Link href="/login">Sign in</Link></span></header><main className="pricing"><p className="eyebrow">Start with the right foundation</p><h1>Choose a CRM plan for your team</h1><p className="lead">Start your 14-day trial. You can change your plan as your team grows.</p><div className="cadence" aria-label="Billing cadence"><Link className={cadence === "monthly" ? "active" : ""} href={`/select-plan?${query(chosen.plan, "monthly")}`}>Monthly</Link><Link className={cadence === "annual" ? "active" : ""} href={`/select-plan?${query(chosen.plan, "annual")}`}>Annual</Link></div><div className="plan-grid">{Object.entries(plans).map(([key, plan]) => { const active = key === chosen.plan; return <article className={`plan-card ${active ? "selected" : ""}`} key={key}>{active && <span className="selected-label"><Check /> Selected</span>}<h2>{plan.name}</h2><p>For {key === "essentials" ? "individuals getting organized" : key === "growth" ? "growing revenue teams" : "teams coordinating at scale"}.</p><p className="plan-price"><b>${plan[cadence]}</b><span>/ user / month</span></p><p>Includes {plan.seats} {plan.seats === 1 ? "user" : "users"}</p><ul><li><Check /> Contact and lead records</li><li><Check /> Pipeline management</li><li><Check /> Tasks and activities</li></ul><Link className="primary link-button" href={`/register?${query(key as keyof typeof plans, cadence)}`}>Start with {plan.name}</Link></article>; })}<article className="plan-card"><h2>Enterprise</h2><p>For organizations needing tailored governance and support.</p><p className="plan-price"><b>Custom</b><span>pricing</span></p><ul><li><Check /> Advanced controls</li><li><Check /> Guided rollout</li><li><Check /> Custom terms</li></ul><a className="secondary link-button" href="mailto:info@nexaflowsystems.com?subject=NexaFlow%20Enterprise">Contact sales</a></article></div><p className="pricing-note">No credit card required for the preview. Production billing is not connected.</p></main><Footer /></div>; }
