import {expect,test,type Page} from "playwright/test";
import {Pool}from"pg";
import{keyedHash}from"../../src/server/security/crypto";
const db=new Pool({connectionString:process.env.DATABASE_URL||"postgres://nexaflow:nexaflow@127.0.0.1:54329/nexaflow"}),secret="local-only-session-secret-change-me-32chars";
async function fixture(page:Page){
 const suffix=crypto.randomUUID(),emails=[`owner-${suffix}@test`,`member-${suffix}@test`,`admin-${suffix}@test`],users=(await db.query(`insert into users(primary_email_normalized,primary_email_display,display_name,status,email_verified_at)values($1,$1,'WI2 Owner','active',now()),($2,$2,'WI2 Member','active',now()),($3,$3,'WI2 Admin','active',now())returning id`,emails)).rows,workspace=(await db.query(`insert into workspaces(name,slug,status,plan_code,billing_cadence,created_by_user_id)values('WI2 Browser',$1,'active','growth','monthly',$2)returning id`,[`wi2-${suffix}`,users[0].id])).rows[0],roles=(await db.query(`insert into roles(workspace_id,code,permissions,is_system,policy_version)values($1,'owner','{}',true,'tenant-admin-v1'),($1,'admin','{}',true,'tenant-admin-v1'),($1,'member','{}',true,'tenant-admin-v1')returning id,code`,[workspace.id])).rows,role=(code:string)=>roles.find(value=>value.code===code).id,members=(await db.query(`insert into workspace_memberships(workspace_id,user_id,role_id,status)values($1,$2,$5,'active'),($1,$3,$6,'active'),($1,$4,$7,'active')returning id`,[workspace.id,users[0].id,users[1].id,users[2].id,role("owner"),role("member"),role("admin")])).rows;
 await db.query(`insert into workspace_entitlement_snapshots(workspace_id,plan_code,catalog_version,effective_feature_flags,effective_limits)values($1,'growth','wi2','{}','{"activeSeats":10}')`,[workspace.id]);const token=`wi2-${crypto.randomUUID()}`;await db.query(`insert into sessions(user_id,session_hash,security_version,idle_expires_at,absolute_expires_at,authenticated_at,auth_method)values($1,$2,1,now()+interval '1 hour',now()+interval '1 day',now(),'password')`,[users[0].id,keyedHash(token,secret)]);await page.context().addCookies([{name:"nexaflow_session",value:token,url:"http://127.0.0.1:3000"}]);return{users,roles,members,role};
}
test.afterAll(async()=>db.end());
test("confirms elevation, restores focus, reloads stale authority, and constrains Admin invitations",async({page})=>{
 const f=await fixture(page);await page.goto("/workspace/settings/people");const member=page.getByRole("row").filter({hasText:"WI2 Member"}),select=member.getByLabel("Role for WI2 Member");await select.selectOption("admin");const dialog=page.getByRole("alertdialog",{name:"Change WI2 Member to Admin?"});await expect(dialog).toContainText("This changes what they can access and manage in the workspace.");await expect(page.getByRole("button",{name:"Cancel"})).toBeFocused();await page.keyboard.press("Escape");await expect(select).toBeFocused();await select.selectOption("admin");await page.getByRole("button",{name:"Save role"}).click();await expect(page.getByText("WI2 Member’s role changed to Admin.")).toBeVisible();
 await db.query("update workspace_memberships set role_id=$1 where id=$2",[f.role("owner"),f.members[2].id]);await db.query("update workspace_memberships set role_id=$1 where id=$2",[f.role("admin"),f.members[0].id]);await select.selectOption("member");await expect(page.getByText("Your permissions changed while you were viewing this page. Reloading the latest roles and permissions.")).toBeVisible();await expect(page.getByText("Latest roles and permissions loaded.")).toBeVisible();
 const token=`wi2-admin-${crypto.randomUUID()}`;await db.query(`insert into sessions(user_id,session_hash,security_version,idle_expires_at,absolute_expires_at,authenticated_at,auth_method)values($1,$2,1,now()+interval '1 hour',now()+interval '1 day',now(),'password')`,[f.users[0].id,keyedHash(token,secret)]);await page.context().clearCookies();await page.context().addCookies([{name:"nexaflow_session",value:token,url:"http://127.0.0.1:3000"}]);await page.goto("/workspace/settings/invite");await expect(page.getByLabel("Default role").locator("option")).toHaveCount(1);await expect(page.getByLabel("Default role")).toHaveValue("member");
});
test("remains usable at 320px and browser 200 percent zoom",async({page})=>{
 await fixture(page);await page.setViewportSize({width:320,height:700});await page.goto("/workspace/settings/people");const session=await page.context().newCDPSession(page);await session.send("Emulation.setPageScaleFactor",{pageScaleFactor:2});await expect(page.getByRole("heading",{name:"People and roles"})).toBeVisible();const wrapper=page.locator(".table-wrap");await expect(wrapper).toBeVisible();expect(await wrapper.evaluate(node=>node.scrollWidth>=node.clientWidth)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
});
