import{expect,test,type BrowserContext,type Page}from"playwright/test";import{Pool}from"pg";import{keyedHash}from"../../src/server/security/crypto";
const db=new Pool({connectionString:process.env.DATABASE_URL||"postgres://nexaflow:nexaflow@127.0.0.1:54329/nexaflow"}),secret="local-only-session-secret-change-me-32chars";
async function setup(context:BrowserContext){const suffix=crypto.randomUUID(),users=(await db.query(`insert into users(primary_email_normalized,primary_email_display,display_name,status,email_verified_at)values($1,$1,'Stale Owner','active',now()),($2,$2,'Stale Target','active',now())returning id`,[`stale-owner-${suffix}@test`,`stale-target-${suffix}@test`])).rows,workspace=(await db.query(`insert into workspaces(name,slug,status,plan_code,billing_cadence,created_by_user_id)values('Stale Browser',$1,'active','growth','monthly',$2)returning id`,[`stale-${suffix}`,users[0].id])).rows[0],roles=(await db.query(`insert into roles(workspace_id,code,permissions,is_system,policy_version)values($1,'owner','{}',true,'tenant-admin-v1'),($1,'admin','{}',true,'tenant-admin-v1'),($1,'member','{}',true,'tenant-admin-v1')returning id,code`,[workspace.id])).rows,role=(code:string)=>roles.find(row=>row.code===code).id,members=(await db.query(`insert into workspace_memberships(workspace_id,user_id,role_id,status)values($1,$2,$4,'active'),($1,$3,$5,'active')returning id,version`,[workspace.id,users[0].id,users[1].id,role("owner"),role("member")])).rows,token=`stale-${crypto.randomUUID()}`;await db.query(`insert into sessions(user_id,session_hash,security_version,idle_expires_at,absolute_expires_at,authenticated_at,auth_method)values($1,$2,1,now()+interval '1 hour',now()+interval '1 day',now(),'password')`,[users[0].id,keyedHash(token,secret)]);await context.addCookies([{name:"nexaflow_session",value:token,url:"http://127.0.0.1:3000"}]);return{members}}
const select=(page:Page)=>page.getByRole("row").filter({hasText:"Stale Target"}).getByLabel("Role for Stale Target");
test.afterAll(async()=>db.end());
test.beforeEach(async()=>db.query("delete from idempotency_records where operation='membership_role_change'"));
test("concurrent edits conflict, reload, and retry exactly once",async({context,page})=>{const f=await setup(context),other=await context.newPage();await page.goto("/workspace/settings/people");await other.goto("/workspace/settings/people");await select(page).selectOption("admin");await page.getByRole("button",{name:"Save role"}).click();await expect(page.getByText("Stale Target’s role changed to Admin.")).toBeVisible();await select(other).selectOption("admin");await other.getByRole("button",{name:"Save role"}).click();await expect(other.getByText(/Reload the latest roles and permissions before retrying/)).toBeVisible();await other.getByRole("button",{name:"Reload latest"}).click();await expect(other.getByText("Latest values loaded.")).toBeVisible();await select(other).selectOption("member");await expect(other.getByText("Stale Target’s role changed to Member.")).toBeVisible();expect((await db.query(`select count(*)::int count from audit_events where target_id=$1 and action='workspace.membership_changed' and outcome='success'`,[f.members[1].id])).rows[0].count).toBe(2);expect((await db.query(`select count(*)::int count from idempotency_records where operation='membership_role_change'`)).rows[0].count).toBe(2)});
test("suspension automatically reconciles stale controls after denial",async({context,page})=>{const f=await setup(context);await page.goto("/workspace/settings/people");await db.query("update workspace_memberships set status='suspended',version=version+1 where id=$1",[f.members[1].id]);await select(page).selectOption("admin");await page.getByRole("button",{name:"Save role"}).click();await expect(page.getByText("Latest roles and permissions loaded.")).toBeVisible();const row=page.getByRole("row").filter({hasText:"Stale Target"});await expect(row.getByText("suspended",{exact:true})).toBeVisible();await expect(row.getByRole("combobox")).toHaveCount(0)});
test("removal automatically reconciles stale controls after denial",async({context,page})=>{const f=await setup(context);await page.goto("/workspace/settings/people");await db.query("update workspace_memberships set status='removed',version=version+1 where id=$1",[f.members[1].id]);await select(page).selectOption("admin");await page.getByRole("button",{name:"Save role"}).click();await expect(page.getByText("Latest roles and permissions loaded.")).toBeVisible();const row=page.getByRole("row").filter({hasText:"Stale Target"});await expect(row.getByText("removed",{exact:true})).toBeVisible();await expect(row.getByRole("combobox")).toHaveCount(0)});
