"use client";

import Link from "next/link";
import { FormEvent, type ReactNode, useEffect, useRef, useState } from "react";
import { ActionLink, Button, DataTable, EmptyState, FeedbackState, FieldMessage, Panel, StatusBadge, ViewTabs } from "@/frontend/design-system";
import {
  COMPANY_CREATE, COMPANY_EDIT, COMPANY_LIFECYCLE, CONTACT_CREATE, CONTACT_EDIT, CONTACT_LIFECYCLE,
  companyCreateCommandV1Schema, companyEditCommandV1Schema, companyResultEnvelopeSchema,
  contactAffiliationReplaceCommandV1Schema, contactCreateCommandV1Schema, contactEditCommandV1Schema, contactResultEnvelopeSchema,
  customerGraphDetailEnvelopeSchema, customerGraphErrorEnvelopeV1Schema, customerGraphListEnvelopeSchema,
  type CustomerGraphDetail, type CustomerGraphError, type CustomerGraphKind, type CustomerGraphList, type CustomerGraphStatus,
} from "../contracts/customer-graph.contracts";
import { CustomerGraphLoading } from "./customer-graph-feedback";

const authorityLossCodes = new Set(["authentication_required", "permission_required", "resource_not_found", "authority_conflict"]);
const plural = (kind: CustomerGraphKind) => kind === "company" ? "companies" : "contacts";
const title = (kind: CustomerGraphKind) => kind === "company" ? "Companies" : "Contacts";
const itemTitle = (kind: CustomerGraphKind) => kind === "company" ? "Company" : "Contact";
const endpoint = (workspaceId: string, kind: CustomerGraphKind, id?: string) => `/api/workspaces/${workspaceId}/${plural(kind)}${id ? `/${id}` : ""}`;
const statusTone = (status: CustomerGraphStatus) => status === "active" ? "success" as const : "neutral" as const;
export type CustomerGraphErrorDisposition = "authority_loss" | "stale" | "retry_same_request" | "new_request";
export function customerGraphErrorDisposition(error: CustomerGraphError): CustomerGraphErrorDisposition {
  if (authorityLossCodes.has(error.code)) return "authority_loss";
  if (error.code === "stale_version") return "stale";
  return error.reconciliation.action === "retry_same_request" ? "retry_same_request" : "new_request";
}
const isAuthorityLoss = (error: CustomerGraphError) => customerGraphErrorDisposition(error) === "authority_loss";
export function contactChannelPresentation(record: { email: string | null; phone: string | null; maskedEmail: string | null; maskedPhone: string | null; disclosure: { channels: "full" | "masked" } }) {
  const values: Array<[string, string]> = [];
  if (record.disclosure.channels === "full") { if (record.email) values.push(["Email", record.email]); if (record.phone) values.push(["Phone", record.phone]); }
  else { if (record.maskedEmail) values.push(["Email", record.maskedEmail]); if (record.maskedPhone) values.push(["Phone", record.maskedPhone]); }
  const description = record.disclosure.channels === "full" ? "Full contact channels are shown because the server authorized full disclosure." : values.length ? "Only server-authorized masked contact channels are shown." : "Contact channels are unavailable for disclosure.";
  return { mode: record.disclosure.channels === "full" ? "full" as const : values.length ? "masked" as const : "unavailable" as const, values, description };
}
async function responseBody(response: Response): Promise<unknown> { try { return await response.json(); } catch { return null; } }
async function csrf() { const response = await fetch("/api/auth/csrf", { cache: "no-store" }); if (!response.ok) throw new Error("csrf_unavailable"); return (await response.json() as { token: string }).token; }
function requestKey(serialized: string, current: { body: string; key: string }) { return current.body === serialized ? current : { body: serialized, key: crypto.randomUUID() }; }
function safeError(value: unknown): CustomerGraphError { const parsed = customerGraphErrorEnvelopeV1Schema.safeParse(value); return parsed.success ? parsed.data.error : { code: "unexpected_error", message: "The request could not be completed.", retryable: true, reconciliation: { required: true, action: "retry_same_request" } }; }

function SafeAuthorityState({ kind, error, detail = false }: { kind: CustomerGraphKind; error?: CustomerGraphError | null; detail?: boolean }) {
  const back = `/crm/${plural(kind)}`, login = `/login?next=${encodeURIComponent(back)}`;
  return <FeedbackState tone="danger" autoFocus title={detail ? `${itemTitle(kind)} unavailable` : `${title(kind)} unavailable`}
    action={<ActionLink href={error?.code === "authentication_required" ? login : back}>{error?.code === "authentication_required" ? "Sign in again" : `Back to ${title(kind).toLowerCase()}`}</ActionLink>}>
    <p>Your authority changed or this information is no longer available. Protected details, choices, and entries have been cleared.</p>
  </FeedbackState>;
}

export function CustomerGraphListPage({ workspaceId, kind, initialStatus = "active", initialCursor }: { workspaceId: string; kind: CustomerGraphKind; initialStatus?: CustomerGraphStatus; initialCursor?: string }) {
  const [view, setView] = useState<CustomerGraphList | null>(null), [error, setError] = useState<CustomerGraphError | null>(null), [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(null); setView(null); const query = new URLSearchParams({ status: initialStatus, limit: "50" }); if (initialCursor) query.set("cursor", initialCursor);
    fetch(`${endpoint(workspaceId, kind)}?${query}`, { cache: "no-store", signal: controller.signal }).then(async response => { const payload = await responseBody(response); if (!response.ok) throw safeError(payload); const parsed = customerGraphListEnvelopeSchema.safeParse(payload); if (!parsed.success || parsed.data.data.kind !== kind) throw safeError(null); setView(parsed.data.data); }).catch(value => { if (!controller.signal.aborted) { setView(null); setError(value && typeof value === "object" && "code" in value ? value as CustomerGraphError : safeError(null)); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort();
  }, [workspaceId, kind, initialStatus, initialCursor]);
  const base = `/crm/${plural(kind)}`;
  return <><header className="product-page-header crm-page-heading"><div><p className="eyebrow">Customers / {title(kind)}</p><h1>{title(kind)}</h1><p className="lead">Visible {title(kind).toLowerCase()} in the current Workspace. Open a record to see server-authorized details and actions.</p></div>{view?.capabilities.canCreate && <div className="product-page-actions"><ActionLink variant="primary" href={`${base}/new`}>Add {itemTitle(kind).toLowerCase()}</ActionLink></div>}</header>
    <div className="ds-view-row"><ViewTabs label={`${title(kind)} status`} items={[{ href: base, label: "Active", active: initialStatus === "active" }, { href: `${base}?status=archived`, label: "Archived", active: initialStatus === "archived" }]}/></div>
    {loading ? <CustomerGraphLoading label={`Loading ${title(kind).toLowerCase()}…`}/> : error ? isAuthorityLoss(error) ? <SafeAuthorityState kind={kind} error={error}/> : <FeedbackState tone="danger" autoFocus title={`${title(kind)} are temporarily unavailable`} action={<Button onClick={() => location.reload()}>Try again</Button>}><p>{error.message} No protected record details are shown.</p></FeedbackState> : view && <section aria-label={`Visible ${title(kind).toLowerCase()}`}><p role="status" aria-live="polite">{view.items.length} {view.items.length === 1 ? itemTitle(kind).toLowerCase() : title(kind).toLowerCase()} shown.</p>{view.items.length === 0 ? <EmptyState title={`No ${initialStatus} ${title(kind).toLowerCase()}`}><p>There are no server-authorized records in this view.</p>{view.capabilities.canCreate && <ActionLink variant="primary" href={`${base}/new`}>Add {itemTitle(kind).toLowerCase()}</ActionLink>}</EmptyState> : <DataTable caption={`Visible ${title(kind).toLowerCase()}`}><thead><tr><th scope="col">{itemTitle(kind)}</th><th scope="col">Status</th><th scope="col">Updated</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{view.items.map(item => <tr key={item.id}><th scope="row"><Link href={`${base}/${item.id}`}>{item.displayName}</Link></th><td><StatusBadge tone={statusTone(item.status)}>{item.status}</StatusBadge></td><td>{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(item.updatedAt))}</td><td><ActionLink href={`${base}/${item.id}`}>View</ActionLink></td></tr>)}</tbody></DataTable>}{view.nextCursor && <div className="ds-pagination"><ActionLink href={`${base}?${new URLSearchParams({ status: initialStatus, cursor: view.nextCursor })}`}>Next page</ActionLink></div>}</section>}</>;
}

function Facts({ values }: { values: Array<[string, string]> }) { return <dl className="ds-fact-list">{values.map(([name, value]) => <div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>; }

function ConfirmationDialog({ titleId, descriptionId, restoreFocus, onClose, children }: { titleId: string; descriptionId: string; restoreFocus: () => void; onClose: () => void; children: ReactNode }) {
  const dialog = useRef<HTMLDialogElement>(null), restore = useRef(restoreFocus);
  useEffect(() => { restore.current = restoreFocus; }, [restoreFocus]);
  useEffect(() => { const node = dialog.current; if (!node) return; node.showModal(); node.querySelector<HTMLElement>("button")?.focus(); return () => { if (node.open) node.close(); restore.current(); }; }, []);
  return <dialog ref={dialog} className="lead-management-dialog" aria-labelledby={titleId} aria-describedby={descriptionId} onCancel={event => { event.preventDefault(); onClose(); }}>{children}</dialog>;
}

function LifecycleAction({ workspaceId, kind, detail, onAuthorityLoss, onReload }: { workspaceId: string; kind: CustomerGraphKind; detail: CustomerGraphDetail; onAuthorityLoss: (error: CustomerGraphError) => void; onReload: () => Promise<void> }) {
  const record = detail.record, action = record.status === "active" ? "archive" : "restore", allowed = action === "archive" ? record.capabilities.canArchive : record.capabilities.canRestore;
  const [confirming, setConfirming] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [stale, setStale] = useState(false), [applied, setApplied] = useState<{ replayed: boolean } | null>(null),
    trigger = useRef<HTMLButtonElement>(null), alert = useRef<HTMLDivElement>(null), request = useRef({ body: "", key: crypto.randomUUID() });
  if (!allowed) return null;
  async function reloadLatest() { setBusy(true); await onReload(); setStale(false); setMessage("Latest saved record loaded. Review its status before continuing."); setBusy(false); setTimeout(() => alert.current?.focus()); }
  async function mutate() { const command = { contractVersion: kind === "company" ? COMPANY_LIFECYCLE : CONTACT_LIFECYCLE, expectedVersion: record.version }, serialized = JSON.stringify(command); request.current = requestKey(serialized, request.current); setBusy(true); setMessage("");
    try { const token = await csrf(), response = await fetch(`${endpoint(workspaceId, kind, record.id)}/${action}`, { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": token, "idempotency-key": request.current.key }, body: serialized }), payload = await responseBody(response); if (!response.ok) { const error = safeError(payload); if (isAuthorityLoss(error)) { setConfirming(false); onAuthorityLoss(error); return; } if (error.code === "stale_version") { setStale(true); setConfirming(false); request.current = { body: "", key: crypto.randomUUID() }; setMessage(`This ${itemTitle(kind).toLowerCase()} changed. Reload the latest record before trying again.`); setTimeout(() => alert.current?.focus()); return; } setMessage(error.message); setConfirming(false); setTimeout(() => alert.current?.focus()); return; }
      const result = (kind === "company" ? companyResultEnvelopeSchema : contactResultEnvelopeSchema).safeParse(payload); if (!result.success) throw new Error("invalid_result"); setConfirming(false); request.current = { body: "", key: crypto.randomUUID() }; setApplied({ replayed: result.data.data.replayed });
    } catch { setMessage(`We couldn’t ${action} this ${itemTitle(kind).toLowerCase()}. Its saved status is unchanged; retry safely.`); setConfirming(false); setTimeout(() => alert.current?.focus()); } finally { setBusy(false); }
  }
  if (applied) return <FeedbackState tone="success" autoFocus title={applied.replayed ? `${itemTitle(kind)} change was already applied` : `${itemTitle(kind)} ${action === "archive" ? "archived" : "restored"}`} action={<Button onClick={() => location.reload()}>View updated record</Button>}><p>The result was confirmed before this page refreshes.</p></FeedbackState>;
  return <div className="cg-lifecycle">{message && <div ref={alert} className={`ds-feedback ${stale ? "ds-feedback--conflict" : "ds-feedback--info"}`} role={stale ? "alert" : "status"} tabIndex={-1}><div><p>{message}</p></div>{stale && <div className="ds-feedback__actions"><Button onClick={() => void reloadLatest()} disabled={busy}>Reload latest</Button></div>}</div>}<button ref={trigger} className={`ds-action ds-action--${action === "archive" ? "danger" : "secondary"}`} type="button" onClick={() => setConfirming(true)} disabled={stale}>{action === "archive" ? "Archive" : "Restore"}</button>{confirming && <ConfirmationDialog titleId="cg-lifecycle-title" descriptionId="cg-lifecycle-description" restoreFocus={() => trigger.current?.focus()} onClose={() => setConfirming(false)}><h2 id="cg-lifecycle-title">{action === "archive" ? "Archive" : "Restore"} {record.displayName}?</h2><p id="cg-lifecycle-description">{action === "archive" ? "The record and retained history will remain available in Archived." : "The record will return to Active."}</p><div className="ds-page-actions"><Button onClick={() => setConfirming(false)} disabled={busy}>Cancel</Button><Button variant={action === "archive" ? "danger" : "primary"} onClick={() => void mutate()} disabled={busy}>{busy ? `${action === "archive" ? "Archiving" : "Restoring"}…` : action === "archive" ? "Archive record" : "Restore record"}</Button></div></ConfirmationDialog>}</div>;
}

const affiliationRoles = [["employee", "Employee"], ["owner", "Owner"], ["executive", "Executive"], ["decision_maker", "Decision maker"], ["billing", "Billing"], ["technical", "Technical"], ["advisor", "Advisor"], ["contractor", "Contractor"], ["other", "Other"]] as const;
function ContactAffiliationControl({ workspaceId, detail, onAuthorityLoss, onReload }: { workspaceId: string; detail: CustomerGraphDetail; onAuthorityLoss: (error: CustomerGraphError) => void; onReload: () => Promise<void> }) {
  const record = detail.record, contact = "firstName" in record ? record : null, visibleCurrent = contact?.affiliations.find(value => !("companyUnavailable" in value));
  const [companies, setCompanies] = useState<CustomerGraphList["items"]>([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [stale, setStale] = useState(false),
    [message, setMessage] = useState(""), [applied, setApplied] = useState<{ replayed: boolean } | null>(null), alert = useRef<HTMLDivElement>(null), request = useRef({ body: "", key: crypto.randomUUID() }), authorityLoss = useRef(onAuthorityLoss);
  useEffect(() => { authorityLoss.current = onAuthorityLoss; }, [onAuthorityLoss]);
  useEffect(() => { if (!contact?.capabilities.canManageAffiliations) return; const controller = new AbortController(); fetch(`${endpoint(workspaceId, "company")}?status=active&limit=50`, { cache: "no-store", signal: controller.signal }).then(async response => { const payload = await responseBody(response); if (!response.ok) throw safeError(payload); const parsed = customerGraphListEnvelopeSchema.safeParse(payload); if (!parsed.success || parsed.data.data.kind !== "company") throw safeError(null); setCompanies(parsed.data.data.items); }).catch(value => { if (!controller.signal.aborted) { const error = value && typeof value === "object" && "code" in value ? value as CustomerGraphError : safeError(null); if (isAuthorityLoss(error)) authorityLoss.current(error); else setMessage("Available Companies could not be loaded. No affiliation change was made."); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [workspaceId, contact?.capabilities.canManageAffiliations]);
  if (!contact?.capabilities.canManageAffiliations) return null;
  async function reloadLatest() { setBusy(true); await onReload(); setStale(false); setMessage("Latest Contact loaded. Your still-visible Company selection is preserved; review it before saving."); setBusy(false); setTimeout(() => alert.current?.focus()); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget), companyId = String(data.get("companyId") ?? ""), roleCode = String(data.get("roleCode") ?? "other"), command = { contractVersion: "contact-affiliation-replace.v1", expectedVersion: contact!.version, affiliation: companyId ? { companyId, roleCode } : null }, parsed = contactAffiliationReplaceCommandV1Schema.safeParse(command);
    if (!parsed.success) { setMessage("Choose an available Company and role, or choose no affiliation."); alert.current?.focus(); return; } const serialized = JSON.stringify(parsed.data); request.current = requestKey(serialized, request.current); setBusy(true); setMessage("Saving affiliation…");
    try { const token = await csrf(), response = await fetch(`${endpoint(workspaceId, "contact", contact!.id)}/affiliations`, { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": token, "idempotency-key": request.current.key }, body: serialized }), payload = await responseBody(response); if (!response.ok) { const error = safeError(payload); if (isAuthorityLoss(error)) { onAuthorityLoss(error); return; } if (error.code === "stale_version") { setStale(true); request.current = { body: "", key: crypto.randomUUID() }; setMessage("This Contact changed. Reload the latest record before changing its affiliation."); alert.current?.focus(); return; } setMessage(error.message); alert.current?.focus(); return; }
      const result = contactResultEnvelopeSchema.safeParse(payload); if (!result.success) throw new Error("invalid_result"); request.current = { body: "", key: crypto.randomUUID() }; setApplied({ replayed: result.data.data.replayed });
    } catch { setMessage("We couldn’t save the affiliation. The saved affiliation is unchanged; retry safely."); alert.current?.focus(); } finally { setBusy(false); }
  }
  if (applied) return <FeedbackState tone="success" autoFocus title={applied.replayed ? "Affiliation change was already applied" : "Affiliation updated"} action={<Button onClick={() => location.reload()}>View updated Contact</Button>}><p>The confirmed result is ready to display.</p></FeedbackState>;
  const choices: Array<{ id: string; displayName: string }> = companies.map(({ id, displayName }) => ({ id, displayName }));
  if (visibleCurrent && !("companyUnavailable" in visibleCurrent) && !choices.some(value => value.id === visibleCurrent.companyId)) choices.unshift({ id: visibleCurrent.companyId, displayName: visibleCurrent.companyName });
  return <Panel title="Manage Company affiliation" description="Only active Companies visible through the final server-authorized list are offered. Up to 50 are shown.">{message && <div ref={alert} className={`ds-feedback ${stale ? "ds-feedback--conflict" : "ds-feedback--info"}`} role={stale ? "alert" : "status"} tabIndex={-1}><div><p>{message}</p></div>{stale && <div className="ds-feedback__actions"><Button onClick={() => void reloadLatest()} disabled={busy}>Reload latest</Button></div>}</div>}{loading ? <CustomerGraphLoading label="Loading available Companies…"/> : <form className="ds-form" onSubmit={submit}><label className="field" htmlFor="companyId"><span>Company</span><select id="companyId" name="companyId" defaultValue={visibleCurrent && !("companyUnavailable" in visibleCurrent) ? visibleCurrent.companyId : ""}><option value="">No affiliation</option>{choices.map(value => <option value={value.id} key={value.id}>{value.displayName}</option>)}</select></label><label className="field" htmlFor="roleCode"><span>Relationship</span><select id="roleCode" name="roleCode" defaultValue={visibleCurrent && !("companyUnavailable" in visibleCurrent) ? visibleCurrent.roleCode : "other"}>{affiliationRoles.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{contact.affiliations.some(value => "companyUnavailable" in value) && <p className="helper">The current Company is unavailable. Choosing “No affiliation” will end the retained affiliation without revealing it.</p>}<Button variant="primary" disabled={busy || stale}>{busy ? "Saving affiliation…" : "Save affiliation"}</Button></form>}</Panel>;
}

export function CustomerGraphDetailPage({ workspaceId, kind, id }: { workspaceId: string; kind: CustomerGraphKind; id: string }) {
  const [detail, setDetail] = useState<CustomerGraphDetail | null>(null), [error, setError] = useState<CustomerGraphError | null>(null), [loading, setLoading] = useState(true);
  async function load() { const response = await fetch(endpoint(workspaceId, kind, id), { cache: "no-store" }), payload = await responseBody(response); if (!response.ok) throw safeError(payload); const parsed = customerGraphDetailEnvelopeSchema.safeParse(payload); if (!parsed.success || parsed.data.data.kind !== kind || parsed.data.data.record.id !== id) throw safeError(null); setDetail(parsed.data.data); setError(null); }
  useEffect(() => { let active = true; setLoading(true); load().catch(value => { if (active) { setDetail(null); setError(value && typeof value === "object" && "code" in value ? value as CustomerGraphError : safeError(null)); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workspaceId, kind, id]);
  const authorityLost = (value: CustomerGraphError) => { setDetail(null); setError(value); };
  const reload = async () => { try { await load(); } catch (value) { const next = value && typeof value === "object" && "code" in value ? value as CustomerGraphError : safeError(null); if (isAuthorityLoss(next)) authorityLost(next); else setError(next); } };
  const base = `/crm/${plural(kind)}`;
  if (loading) return <CustomerGraphLoading label={`Loading ${itemTitle(kind).toLowerCase()}…`}/>;
  if (error || !detail) return error && isAuthorityLoss(error) ? <SafeAuthorityState kind={kind} error={error} detail/> : <FeedbackState tone="danger" autoFocus title={`${itemTitle(kind)} is temporarily unavailable`} action={<ActionLink href={base}>Back to {title(kind).toLowerCase()}</ActionLink>}><p>No protected details are shown. Try again safely.</p></FeedbackState>;
  const record = detail.record, legacy = record.authorityContractVersion === "legacy-p1a-root-v1", companyRecord = "domain" in record ? record : null, contactRecord = "firstName" in record ? record : null,
    channelPresentation = contactRecord ? contactChannelPresentation(contactRecord) : null;
  return <><header className="product-page-header"><div><p className="eyebrow">{title(kind)} / Details</p><h1>{record.displayName}</h1><p className="lead">Server-authorized information for the current Workspace.</p></div><StatusBadge tone={statusTone(record.status)}>{record.status}</StatusBadge></header>
    {legacy && <FeedbackState tone="warning" title="Read-only legacy record"><p>This record remains visible as retained authority. Editing, lifecycle changes, and affiliation management are unavailable. No adoption or backfill action is offered.</p></FeedbackState>}
    <div className="ds-detail-layout"><Panel title={`${itemTitle(kind)} record`}><Facts values={[["Status", record.status], ["Updated", new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(record.updatedAt))], ["Visibility", record.visibility === "workspace" ? "Workspace" : "Selected Teams"]]}/></Panel>
      {companyRecord?.disclosure.domain === "full" && companyRecord.domain && <Panel title="Authorized domain"><Facts values={[["Domain", companyRecord.domain]]}/></Panel>}
      {contactRecord && channelPresentation && <Panel title="Contact channels" description={channelPresentation.description}>{channelPresentation.values.length ? <Facts values={channelPresentation.values}/> : <p className="helper">No contact channels are available.</p>}</Panel>}
      {contactRecord && <Panel title="Company affiliation" description="Company details appear only when the server authorizes their presentation.">{contactRecord.affiliations.length ? <ul className="cg-affiliations">{contactRecord.affiliations.map((value, index) => "companyUnavailable" in value ? <li key={`unavailable-${index}`}>Company unavailable</li> : <li key={value.affiliationId}>{value.companyName} · {value.roleCode.replaceAll("_", " ")}</li>)}</ul> : <p className="helper">No current affiliation is available.</p>}</Panel>}
    </div>{contactRecord && <ContactAffiliationControl workspaceId={workspaceId} detail={detail} onAuthorityLoss={authorityLost} onReload={reload}/>}<div className="ds-page-actions"><ActionLink href={base}>Back to {title(kind).toLowerCase()}</ActionLink>{!legacy && record.capabilities.canEdit && (companyRecord?.disclosure.domain === "full" || contactRecord?.disclosure.channels === "full") && <ActionLink variant="primary" href={`${base}/${id}/edit`}>Edit {itemTitle(kind).toLowerCase()}</ActionLink>}<LifecycleAction workspaceId={workspaceId} kind={kind} detail={detail} onAuthorityLoss={authorityLost} onReload={reload}/></div></>;
}

type FieldErrors = Record<string, string>;
const fieldLabels: Record<string, string> = { displayName: "Company name", domain: "Domain", firstName: "First name", lastName: "Last name", email: "Email", phone: "Phone", responsibleMembershipId: "Responsible person", responsibleTeamId: "Responsible Team", visibility: "Visibility", visibleTeamIds: "Visible Teams", affiliation: "Company affiliation", _form: "Form" };
export function CustomerGraphFormPage({ workspaceId, kind, id }: { workspaceId: string; kind: CustomerGraphKind; id?: string }) {
  const editing = Boolean(id), [detail, setDetail] = useState<CustomerGraphDetail | null>(null), [canCreate, setCanCreate] = useState(false), [loading, setLoading] = useState(true), [authorityError, setAuthorityError] = useState<CustomerGraphError | null>(null),
    [busy, setBusy] = useState(false), [notice, setNotice] = useState(""), [errors, setErrors] = useState<FieldErrors>({}), [stale, setStale] = useState(false), [saved, setSaved] = useState<{ id: string; replayed: boolean } | null>(null),
    summary = useRef<HTMLDivElement>(null), form = useRef<HTMLFormElement>(null), request = useRef({ body: "", key: crypto.randomUUID() });
  function clearProtected(error: CustomerGraphError) { form.current?.reset(); setDetail(null); setCanCreate(false); setNotice(""); setErrors({}); setStale(false); setSaved(null); request.current = { body: "", key: crypto.randomUUID() }; setAuthorityError(error); }
  async function loadAuthority() { if (!id) { const response = await fetch(`${endpoint(workspaceId, kind)}?bootstrap=true`, { cache: "no-store" }), payload = await responseBody(response); if (!response.ok) throw safeError(payload); const parsed = customerGraphListEnvelopeSchema.safeParse(payload); if (!parsed.success || parsed.data.data.kind !== kind || parsed.data.data.items.length || parsed.data.data.nextCursor !== null) throw safeError(null); if (!parsed.data.data.capabilities.canCreate) throw { code: "permission_required", message: "This action is not available.", retryable: false, reconciliation: { required: false, action: "none" } } satisfies CustomerGraphError; setCanCreate(true); return; }
    const response = await fetch(endpoint(workspaceId, kind, id), { cache: "no-store" }), payload = await responseBody(response); if (!response.ok) throw safeError(payload); const parsed = customerGraphDetailEnvelopeSchema.safeParse(payload); if (!parsed.success || parsed.data.data.kind !== kind || !parsed.data.data.record.capabilities.canEdit || parsed.data.data.record.authorityContractVersion !== "customer-graph-v1") throw safeError(null); const record = parsed.data.data.record; if (kind === "company" && (!("domain" in record) || record.disclosure.domain !== "full") || kind === "contact" && (!("firstName" in record) || record.disclosure.channels !== "full")) throw safeError(null); setDetail(parsed.data.data);
  }
  useEffect(() => { let active = true; setLoading(true); loadAuthority().catch(value => { if (active) clearProtected(value && typeof value === "object" && "code" in value ? value as CustomerGraphError : safeError(null)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workspaceId, kind, id]);
  const base = `/crm/${plural(kind)}`;
  if (loading) return <CustomerGraphLoading label={`Checking permission to ${editing ? "edit" : "add"} ${itemTitle(kind).toLowerCase()}…`}/>;
  if (authorityError || editing && !detail || !editing && !canCreate) return <SafeAuthorityState kind={kind} error={authorityError} detail/>;
  if (saved) return <FeedbackState tone="success" autoFocus title={saved.replayed ? `${itemTitle(kind)} save was already applied` : `${itemTitle(kind)} saved`} action={<ActionLink variant="primary" href={`${base}/${saved.id}`}>View {itemTitle(kind).toLowerCase()}</ActionLink>}><p>The server confirmed this result. No automatic navigation occurred before the announcement.</p></FeedbackState>;
  async function reloadLatest() { setBusy(true); try { await loadAuthority(); setStale(false); setNotice("Latest saved version loaded. Your entries were preserved; review them before saving."); request.current = { body: "", key: crypto.randomUUID() }; setTimeout(() => summary.current?.focus()); } catch (value) { const error = value && typeof value === "object" && "code" in value ? value as CustomerGraphError : safeError(null); if (isAuthorityLoss(error)) clearProtected(error); else { setNotice("The latest record could not be loaded. Your entries are preserved, but saving remains disabled."); setTimeout(() => summary.current?.focus()); } } finally { setBusy(false); } }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget), nullable = (name: string) => String(data.get(name) ?? "").trim() || null,
    assignment = detail?.record.capabilities.canManageAssignment ? { responsibleMembershipId: nullable("responsibleMembershipId"), responsibleTeamId: nullable("responsibleTeamId"), visibility: data.get("visibility") === "teams" ? "teams" as const : "workspace" as const, visibleTeamIds: data.get("visibility") === "teams" ? data.getAll("visibleTeamIds").map(String) : [] }
      : detail ? { responsibleMembershipId: detail.record.responsibleMembershipId, responsibleTeamId: detail.record.responsibleTeamId, visibility: detail.record.visibility, visibleTeamIds: detail.record.visibleTeamIds } : { responsibleMembershipId: null, responsibleTeamId: null, visibility: "workspace" as const, visibleTeamIds: [] as string[] };
    const command = kind === "company" ? { contractVersion: editing ? COMPANY_EDIT : COMPANY_CREATE, ...(editing ? { expectedVersion: detail!.record.version } : {}), displayName: String(data.get("displayName") ?? ""), domain: nullable("domain"), ...assignment } : { contractVersion: editing ? CONTACT_EDIT : CONTACT_CREATE, ...(editing ? { expectedVersion: detail!.record.version } : {}), firstName: String(data.get("firstName") ?? ""), lastName: nullable("lastName"), email: nullable("email"), phone: nullable("phone"), ...(!editing ? { affiliation: null } : {}), ...assignment };
    const schema = kind === "company" ? editing ? companyEditCommandV1Schema : companyCreateCommandV1Schema : editing ? contactEditCommandV1Schema : contactCreateCommandV1Schema, parsed = schema.safeParse(command);
    if (!parsed.success) { const next: FieldErrors = {}; for (const issue of parsed.error.issues) next[String(issue.path[0] ?? "_form")] ??= "Review this value."; setErrors(next); setNotice("Please correct the linked fields below."); setTimeout(() => summary.current?.focus()); return; }
    const serialized = JSON.stringify(parsed.data); request.current = requestKey(serialized, request.current); setBusy(true); setErrors({}); setNotice(editing ? `Saving ${itemTitle(kind).toLowerCase()}…` : `Creating ${itemTitle(kind).toLowerCase()}…`);
    try { const token = await csrf(), response = await fetch(endpoint(workspaceId, kind, id), { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json", "x-csrf-token": token, "idempotency-key": request.current.key }, body: serialized }), payload = await responseBody(response); if (!response.ok) { const error = safeError(payload); if (isAuthorityLoss(error)) { clearProtected(error); return; } if (error.code === "stale_version") { setStale(true); request.current = { body: "", key: crypto.randomUUID() }; setNotice(`This ${itemTitle(kind).toLowerCase()} changed. Reload the latest version before saving again.`); setTimeout(() => summary.current?.focus()); return; } if (error.code === "idempotency_conflict") request.current = { body: "", key: crypto.randomUUID() }; setNotice(error.message); setTimeout(() => summary.current?.focus()); return; }
      const companyResult = companyResultEnvelopeSchema.safeParse(payload), contactResult = contactResultEnvelopeSchema.safeParse(payload), result = kind === "company" && companyResult.success ? companyResult.data.data : kind === "contact" && contactResult.success ? contactResult.data.data : null, recordId = result && ("companyId" in result ? result.companyId : result.contactId); if (!recordId || !result) throw new Error("invalid_result"); request.current = { body: "", key: crypto.randomUUID() }; setSaved({ id: recordId, replayed: result.replayed });
    } catch { setNotice(`We couldn’t save this ${itemTitle(kind).toLowerCase()}. Your entries are still here; retry safely.`); setTimeout(() => summary.current?.focus()); } finally { setBusy(false); }
  }
  const record = detail?.record, companyRecord = record && "domain" in record ? record : null, contactRecord = record && "firstName" in record ? record : null;
  const described = (name: string, help = false) => [help ? `${name}-help` : "", errors[name] ? `${name}-error` : ""].filter(Boolean).join(" ") || undefined;
  return <><header className="product-page-header"><div><p className="eyebrow">{title(kind)} / {editing ? "Edit" : "New"}</p><h1>{editing ? `Edit ${itemTitle(kind).toLowerCase()}` : `Add ${itemTitle(kind).toLowerCase()}`}</h1><p className="lead">Required values are validated before this record is saved to the current Workspace.</p></div></header>
    {notice && <div ref={summary} className={`ds-feedback ${Object.keys(errors).length || stale ? "ds-feedback--conflict" : "ds-feedback--info"}`} role={Object.keys(errors).length || stale ? "alert" : "status"} tabIndex={-1}><div><p>{notice}</p>{Object.keys(errors).length > 0 && <ul>{Object.entries(errors).map(([name, message]) => <li key={name}>{name === "_form" ? message : <a href={`#${name}`} onClick={() => setTimeout(() => document.getElementById(name)?.focus())}>{fieldLabels[name] ?? name}: {message}</a>}</li>)}</ul>}</div>{stale && <div className="ds-feedback__actions"><Button type="button" onClick={() => void reloadLatest()} disabled={busy}>Reload latest</Button></div>}</div>}
    <Panel title={`${itemTitle(kind)} information`} description={kind === "contact" ? "Contact channels are submitted securely and redisplayed only when the server authorizes full or masked disclosure." : undefined}><form ref={form} className="ds-form" onSubmit={submit} noValidate aria-busy={busy}>
      {kind === "company" ? <><label className="field" htmlFor="displayName"><span>Company name</span><input id="displayName" name="displayName" autoComplete="organization" defaultValue={record?.displayName ?? ""} aria-invalid={Boolean(errors.displayName)} aria-describedby={described("displayName")}/>{errors.displayName && <FieldMessage id="displayName-error" tone="error">{errors.displayName}</FieldMessage>}</label><label className="field" htmlFor="domain"><span>Domain <small>optional</small></span><input id="domain" name="domain" inputMode="url" defaultValue={companyRecord?.disclosure.domain === "full" ? companyRecord.domain ?? "" : ""} aria-invalid={Boolean(errors.domain)} aria-describedby={described("domain", true)}/><FieldMessage id="domain-help">Enter a domain such as example.com, without a protocol or path.</FieldMessage>{errors.domain && <FieldMessage id="domain-error" tone="error">{errors.domain}</FieldMessage>}</label></> : <><div className="form-grid"><label className="field" htmlFor="firstName"><span>First name</span><input id="firstName" name="firstName" autoComplete="given-name" defaultValue={contactRecord?.firstName ?? ""} aria-invalid={Boolean(errors.firstName)} aria-describedby={described("firstName")}/>{errors.firstName && <FieldMessage id="firstName-error" tone="error">{errors.firstName}</FieldMessage>}</label><label className="field" htmlFor="lastName"><span>Last name <small>optional</small></span><input id="lastName" name="lastName" autoComplete="family-name" defaultValue={contactRecord?.lastName ?? ""} aria-invalid={Boolean(errors.lastName)} aria-describedby={described("lastName")}/>{errors.lastName && <FieldMessage id="lastName-error" tone="error">{errors.lastName}</FieldMessage>}</label></div><div className="form-grid"><label className="field" htmlFor="email"><span>Email <small>optional</small></span><input id="email" name="email" type="email" autoComplete="email" defaultValue={contactRecord?.disclosure.channels === "full" ? contactRecord.email ?? "" : ""} aria-invalid={Boolean(errors.email)} aria-describedby={described("email")}/>{errors.email && <FieldMessage id="email-error" tone="error">{errors.email}</FieldMessage>}</label><label className="field" htmlFor="phone"><span>Phone <small>optional</small></span><input id="phone" name="phone" type="tel" inputMode="tel" autoComplete="tel" defaultValue={contactRecord?.disclosure.channels === "full" ? contactRecord.phone ?? "" : ""} placeholder="+14165550123" aria-invalid={Boolean(errors.phone)} aria-describedby={described("phone", true)}/><FieldMessage id="phone-help">Use international format, for example +14165550123.</FieldMessage>{errors.phone && <FieldMessage id="phone-error" tone="error">{errors.phone}</FieldMessage>}</label></div></>}
      {detail?.record.capabilities.canManageAssignment && <section aria-labelledby="assignment-title"><h2 id="assignment-title">Responsibility and visibility</h2><div className="form-grid"><label className="field" htmlFor="responsibleMembershipId"><span>Responsible person</span><select id="responsibleMembershipId" name="responsibleMembershipId" defaultValue={detail.record.responsibleMembershipId ?? ""} aria-invalid={Boolean(errors.responsibleMembershipId)} aria-describedby={described("responsibleMembershipId")}><option value="">Unassigned</option>{detail.options.responsibleMemberships.map(value => <option key={value.id} value={value.id}>{value.label}</option>)}</select>{errors.responsibleMembershipId && <FieldMessage id="responsibleMembershipId-error" tone="error">{errors.responsibleMembershipId}</FieldMessage>}</label><label className="field" htmlFor="responsibleTeamId"><span>Responsible Team</span><select id="responsibleTeamId" name="responsibleTeamId" defaultValue={detail.record.responsibleTeamId ?? ""} aria-invalid={Boolean(errors.responsibleTeamId)} aria-describedby={described("responsibleTeamId")}><option value="">No responsible Team</option>{detail.options.teams.map(value => <option key={value.id} value={value.id}>{value.label}</option>)}</select>{errors.responsibleTeamId && <FieldMessage id="responsibleTeamId-error" tone="error">{errors.responsibleTeamId}</FieldMessage>}</label></div><fieldset aria-invalid={Boolean(errors.visibility)} aria-describedby={errors.visibility ? "visibility-error" : undefined}><legend>Who can view this record?</legend><label className="check"><input type="radio" name="visibility" value="workspace" defaultChecked={detail.record.visibility === "workspace"}/>Everyone with access to this Workspace</label><label className="check"><input type="radio" name="visibility" value="teams" defaultChecked={detail.record.visibility === "teams"}/>Authorized members of selected Teams</label>{errors.visibility && <FieldMessage id="visibility-error" tone="error">{errors.visibility}</FieldMessage>}</fieldset><fieldset aria-describedby={`visibleTeamIds-help${errors.visibleTeamIds ? " visibleTeamIds-error" : ""}`} aria-invalid={Boolean(errors.visibleTeamIds)}><legend>Visible Teams</legend>{detail.options.teams.map(value => <label className="check" key={value.id}><input type="checkbox" name="visibleTeamIds" value={value.id} defaultChecked={detail.record.visibleTeamIds.includes(value.id)}/>{value.label}</label>)}<FieldMessage id="visibleTeamIds-help">Team visibility requires at least one eligible Team. The responsible Team must also be selected.</FieldMessage>{errors.visibleTeamIds && <FieldMessage id="visibleTeamIds-error" tone="error">{errors.visibleTeamIds}</FieldMessage>}</fieldset></section>}
      <div className="ds-page-actions"><Button variant="primary" disabled={busy || stale}>{busy ? "Saving…" : editing ? "Save changes" : `Add ${itemTitle(kind).toLowerCase()}`}</Button><ActionLink href={id ? `${base}/${id}` : base}>Cancel</ActionLink></div></form></Panel></>;
}
