import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { Pool } from "pg";
import { CrmHomeError, crmHome } from "../src/server/crm/home";

const suite=process.env.RUN_DB_INTEGRATION==="1"?describe:describe.skip;
const pool=new Pool({connectionString:process.env.DATABASE_URL||"postgres://nexaflow:nexaflow@127.0.0.1:54329/nexaflow"});
const now=new Date("2026-08-21T12:00:00.000Z");

async function fixture(){
  const users=(await pool.query(`insert into users(primary_email_normalized,display_name,status,email_verified_at) values ('home-owner@test.example','Owner','active',now()),('home-member@test.example','Member','active',now()),('home-other@test.example','Other','active',now()) returning id`)).rows;
  const workspaces=(await pool.query(`insert into workspaces(name,slug,status,plan_code,billing_cadence,created_by_user_id) values ('Dashboard One','dashboard-one','active','growth','monthly',$1),('Dashboard Other','dashboard-other','active','growth','monthly',$2) returning id`,[users[0].id,users[2].id])).rows;
  async function roles(workspaceId:string){return Object.fromEntries((await pool.query(`insert into roles(workspace_id,code,permissions,is_system) values ($1,'owner','{}',true),($1,'admin','{}',true),($1,'member','{}',true) returning id,code`,[workspaceId])).rows.map(row=>[row.code,row.id]))}
  const oneRoles=await roles(workspaces[0].id),otherRoles=await roles(workspaces[1].id);
  const owner=(await pool.query(`insert into workspace_memberships(workspace_id,user_id,role_id,status) values ($1,$2,$3,'active') returning id`,[workspaces[0].id,users[0].id,oneRoles.owner])).rows[0];
  const member=(await pool.query(`insert into workspace_memberships(workspace_id,user_id,role_id,status) values ($1,$2,$3,'active') returning id`,[workspaces[0].id,users[1].id,oneRoles.member])).rows[0];
  const other=(await pool.query(`insert into workspace_memberships(workspace_id,user_id,role_id,status) values ($1,$2,$3,'active') returning id`,[workspaces[1].id,users[2].id,otherRoles.owner])).rows[0];
  async function session(userId:string){return (await pool.query(`insert into sessions(user_id,session_hash,idle_expires_at,absolute_expires_at,auth_method) values ($1,$2,'2027-01-01','2027-01-02','password') returning id`,[userId,crypto.randomUUID()])).rows[0]}
  const ownerSession=await session(users[0].id),memberSession=await session(users[1].id),otherSession=await session(users[2].id);
  const teams=(await pool.query(`insert into teams(workspace_id,name,name_normalized,status,created_by_membership_id) values ($1,'Sales','sales','active',$2),($1,'Hidden','hidden','active',$2),($3,'Other','other','active',$4) returning id,name`,[workspaces[0].id,owner.id,workspaces[1].id,other.id])).rows;
  const sales=teams.find(row=>row.name==="Sales"),hidden=teams.find(row=>row.name==="Hidden"),otherTeam=teams.find(row=>row.name==="Other");
  await pool.query(`insert into team_memberships(workspace_id,team_id,workspace_membership_id,created_by_membership_id) values ($1,$2,$3,$4)`,[workspaces[0].id,sales.id,member.id,owner.id]);
  const stages=(await pool.query(`insert into pipeline_stages(workspace_id,name,position,status) values ($1,'New',0,'active'),($1,'Qualified',1,'active'),($1,'Legacy',2,'archived'),($2,'Other',0,'active') returning id,name,workspace_id`,[workspaces[0].id,workspaces[1].id])).rows;
  const stage=(name:string)=>stages.find(row=>row.name===name&&row.workspace_id===workspaces[0].id).id;
  async function lead(input:{email:string;owner?:string;visibility?:"workspace"|"teams";team?:string;status?:"open"|"won"|"lost";stage?:string;createdAt?:string;first?:string}){const row=(await pool.query(`insert into leads(workspace_id,first_name,last_name,email_normalized,email_display,company,source,status,stage_id,owner_membership_id,visibility,created_at,updated_at) values ($1,$2,'Lead',$3,$3,'Acme','website',$4,$5,$6,$7,$8,$8) returning id`,[workspaces[0].id,input.first??"Test",input.email,input.status??"open",input.stage??stage("New"),input.owner??owner.id,input.visibility??"workspace",input.createdAt??"2026-08-20T12:00:00Z"])).rows[0];if(input.team)await pool.query(`insert into lead_visible_teams(workspace_id,lead_id,team_id) values ($1,$2,$3)`,[workspaces[0].id,row.id,input.team]);return row}
  const workspaceLead=await lead({email:"workspace@test.example",owner:member.id});
  const ownedLead=await lead({email:"owned@test.example",owner:member.id,visibility:"teams",team:hidden.id,status:"won",stage:stage("Qualified"),createdAt:"2026-08-14T12:00:00Z"});
  const teamLead=await lead({email:"team@test.example",visibility:"teams",team:sales.id,stage:stage("Legacy"),createdAt:"2026-08-14T11:59:59Z"});
  const hiddenLead=await lead({email:"hidden@test.example",visibility:"teams",team:hidden.id,status:"lost"});
  const otherLead=(await pool.query(`insert into leads(workspace_id,first_name,last_name,email_normalized,email_display,company,source,status,stage_id,owner_membership_id,visibility) values ($1,'Other','Lead','other-lead@test.example','other-lead@test.example','Other','website','open',$2,$3,'workspace') returning id`,[workspaces[1].id,stages.find(row=>row.workspace_id===workspaces[1].id).id,other.id])).rows[0];
  await pool.query(`insert into lead_activities(workspace_id,lead_id,kind,body,created_by_membership_id,created_at) values ($1,$2,'note',$3,$4,'2026-08-21T10:00:00Z'),($1,$5,'updated','Hidden newest activity',$4,'2026-08-21T11:00:00Z'),($6,$7,'note','Other tenant activity',$8,'2026-08-21T11:30:00Z')`,[workspaces[0].id,workspaceLead.id,`  Follow up\n${"x".repeat(200)}`,owner.id,hiddenLead.id,workspaces[1].id,otherLead.id,other.id]);
  return {users,workspaces,owner,member,other,ownerSession,memberSession,otherSession,sales,hidden,otherTeam,stages,workspaceLead,ownedLead,teamLead,hiddenLead};
}

suite("CRM home PostgreSQL read model",()=>{
  beforeAll(async()=>pool.query("select 1"));afterAll(async()=>pool.end());
  beforeEach(async()=>pool.query("truncate lead_activities,lead_visible_teams,leads,pipeline_stages,team_memberships,teams,workspace_invitations,audit_events,outbox_messages,idempotency_records,workspace_entitlement_snapshots,workspace_memberships,roles,sessions,identity_credentials,identity_tokens,onboarding_progress,workspaces,users restart identity cascade"));
  it("gives an Owner one tenant-scoped deterministic snapshot without write side effects",async()=>{const f=await fixture(),before=(await pool.query(`select (select count(*) from audit_events) audits,(select count(*) from outbox_messages) outbox,(select count(*) from lead_activities) activities`)).rows[0],model=await crmHome(pool,{userId:f.users[0].id,sessionId:f.ownerSession.id},f.workspaces[0].id,{},now);expect(model.summary).toEqual({visible:4,open:2,won:1,lost:1});expect(model.pipeline.map(row=>[row.name,row.count,row.archived])).toEqual([["New",2,false],["Qualified",1,false],["Legacy",1,true]]);expect(model.recentActivity.map(row=>row.leadId)).not.toContain(f.other.id);expect(model.recentActivity[0].leadId).toBe(f.hiddenLead.id);expect(model.recentActivity.find(row=>row.leadId===f.workspaceLead.id)?.bodyPreview).toHaveLength(160);const after=(await pool.query(`select (select count(*) from audit_events) audits,(select count(*) from outbox_messages) outbox,(select count(*) from lead_activities) activities`)).rows[0];expect(after).toEqual(before)});
  it("re-resolves persisted Member ownership, workspace, and active-team visibility before every aggregate",async()=>{const f=await fixture(),identity={userId:f.users[1].id,sessionId:f.memberSession.id},model=await crmHome(pool,identity,f.workspaces[0].id,{},now);expect(model.summary).toEqual({visible:3,open:2,won:1,lost:0});expect(model.recentActivity.map(row=>row.leadId)).not.toContain(f.hiddenLead.id);await pool.query(`delete from team_memberships where team_id=$1 and workspace_membership_id=$2`,[f.sales.id,f.member.id]);const afterRemoval=await crmHome(pool,identity,f.workspaces[0].id,{},now);expect(afterRemoval.summary.visible).toBe(2);expect(afterRemoval.pipeline.find(row=>row.name==="Legacy")).toBeUndefined();await pool.query(`update teams set status='archived' where id=$1`,[f.hidden.id]);const stillOwned=await crmHome(pool,identity,f.workspaces[0].id,{},now);expect(stillOwned.summary.visible).toBe(2)});
  it("combines filters at the UTC boundary and rejects unauthorized resource IDs and stale access",async()=>{const f=await fixture(),identity={userId:f.users[0].id,sessionId:f.ownerSession.id},at=await crmHome(pool,identity,f.workspaces[0].id,{status:"won",stage:f.stages.find(row=>row.name==="Qualified").id,owner:f.member.id,period:"7d"},now);expect(at.summary).toEqual({visible:1,open:0,won:1,lost:0});const before=await crmHome(pool,identity,f.workspaces[0].id,{period:"7d"},now);expect(before.summary.visible).toBe(3);await expect(crmHome(pool,identity,f.workspaces[0].id,{team:f.otherTeam.id},now)).rejects.toMatchObject({code:"resource_not_found",status:404});await pool.query(`update workspace_memberships set status='suspended' where id=$1`,[f.owner.id]);await expect(crmHome(pool,identity,f.workspaces[0].id,{},now)).rejects.toMatchObject({code:"access_denied"});await pool.query(`update workspace_memberships set status='active' where id=$1`,[f.owner.id]);await pool.query(`update sessions set revoked_at=now() where id=$1`,[f.ownerSession.id]);await expect(crmHome(pool,identity,f.workspaces[0].id,{},now)).rejects.toMatchObject({code:"access_denied"})});
  it("keeps invalid filter errors safe and provider independent",async()=>{const f=await fixture();await expect(crmHome(pool,{userId:f.users[0].id,sessionId:f.ownerSession.id},f.workspaces[0].id,{status:"bogus"},now)).rejects.toBeInstanceOf(CrmHomeError)});
  it("ignores an unrecognized query param end to end instead of failing the dashboard closed",async()=>{const f=await fixture(),identity={userId:f.users[0].id,sessionId:f.ownerSession.id},withJunk=await crmHome(pool,identity,f.workspaces[0].id,{raw_email:"hidden@test.example",utm_source:"newsletter"},now),clean=await crmHome(pool,identity,f.workspaces[0].id,{},now);expect(withJunk.summary).toEqual(clean.summary);expect(withJunk.filters).toEqual(clean.filters)});
  it("summarizes the lifecycle funnel across every definition, zero-count stages included, in display order",async()=>{
    const f=await fixture();
    const definitions=(await pool.query(`select id,code from lead_lifecycle_definitions where status='active'`)).rows;
    const idFor=(code:string)=>definitions.find(row=>row.code===code).id;
    await pool.query(`update leads set lifecycle_definition_id=$1 where id=$2`,[idFor("working"),f.workspaceLead.id]);
    await pool.query(`update leads set lifecycle_definition_id=$1 where id=$2`,[idFor("qualified"),f.ownedLead.id]);
    const model=await crmHome(pool,{userId:f.users[0].id,sessionId:f.ownerSession.id},f.workspaces[0].id,{},now);
    expect(model.lifecycle.map(row=>row.code)).toEqual(["new","working","qualified","disqualified","converted"]);
    expect(Object.fromEntries(model.lifecycle.map(row=>[row.code,row.count]))).toEqual({new:2,working:1,qualified:1,disqualified:0,converted:0});
  });
});
