import { randomUUID } from "node:crypto";
import { afterAll,beforeAll,beforeEach,describe,expect,it } from "vitest";
import { Pool } from "pg";
import { editCompany,getCustomerGraph,listCustomerGraph } from "../src/backend/modules/customer-graph";
import { createSession } from "../src/server/security/session";
import { getServerEnv } from "../src/server/env";
const suite=process.env.RUN_DB_INTEGRATION==="1"?describe:describe.skip,pool=new Pool({connectionString:process.env.DATABASE_URL??"postgres://nexaflow:nexaflow@127.0.0.1:54329/nexaflow"}),env=getServerEnv();
async function fixture(){const user=(await pool.query<{id:string}>(`insert into users(primary_email_normalized,primary_email_display,display_name,status,email_verified_at) values($1,$1,'Graph Owner','active',now()) returning id`,[`graph-${randomUUID()}@test.local`])).rows[0],workspace=(await pool.query<{id:string}>(`insert into workspaces(name,slug,status,plan_code,billing_cadence,created_by_user_id) values('Graph',$1,'active','growth','monthly',$2) returning id`,[`graph-${randomUUID()}`,user.id])).rows[0],role=(await pool.query<{id:string}>(`insert into roles(workspace_id,code,permissions,is_system) values($1,'owner','{}',true) returning id`,[workspace.id])).rows[0],membership=(await pool.query<{id:string}>(`insert into workspace_memberships(workspace_id,user_id,role_id,status) values($1,$2,$3,'active') returning id`,[workspace.id,user.id,role.id])).rows[0],session=await createSession(pool,{userId:user.id,securityVersion:1,secret:env.SESSION_SECRET,idleMinutes:30,absoluteHours:24});
  const operationId=randomUUID(),company=(await pool.query<{id:string;version:number}>(`insert into companies(workspace_id,display_name,name_normalized,domain_normalized,normalization_version,status,visibility,governing_operation_id,created_by_membership_id,updated_by_membership_id,authority_contract_version) values($1,'Before','before','before.test','customer-graph-v1','active','workspace',$2,$3,$3,'customer-graph-v1') returning id,version`,[workspace.id,operationId,membership.id])).rows[0];await pool.query(`insert into company_domain_points(workspace_id,company_id,domain_display,domain_normalized,normalization_version,is_primary,source,governing_operation_id,created_by_membership_id) values($1,$2,'before.test','before.test','customer-graph-v1',true,'manual',$3,$4)`,[workspace.id,company.id,operationId,membership.id]);return{actor:{userId:user.id,sessionId:session.id,workspaceId:workspace.id,membershipId:membership.id,role:"owner" as const},company}}
async function memberActor(workspaceId:string){const user=(await pool.query<{id:string}>(`insert into users(primary_email_normalized,primary_email_display,display_name,status,email_verified_at) values($1,$1,'Graph Member','active',now()) returning id`,[`member-${randomUUID()}@test.local`])).rows[0],role=(await pool.query<{id:string}>(`insert into roles(workspace_id,code,permissions,is_system) values($1,'member','{}',true) on conflict(workspace_id,code) do update set code=excluded.code returning id`,[workspaceId])).rows[0],membership=(await pool.query<{id:string}>(`insert into workspace_memberships(workspace_id,user_id,role_id,status) values($1,$2,$3,'active') returning id`,[workspaceId,user.id,role.id])).rows[0],session=await createSession(pool,{userId:user.id,securityVersion:1,secret:env.SESSION_SECRET,idleMinutes:30,absoluteHours:24});return{userId:user.id,sessionId:session.id,workspaceId,membershipId:membership.id,role:"member" as const}}
async function adminActor(workspaceId:string){const user=(await pool.query<{id:string}>(`insert into users(primary_email_normalized,primary_email_display,display_name,status,email_verified_at) values($1,$1,'Graph Admin','active',now()) returning id`,[`admin-${randomUUID()}@test.local`])).rows[0],role=(await pool.query<{id:string}>(`insert into roles(workspace_id,code,permissions,is_system) values($1,'admin','{}',true) on conflict(workspace_id,code) do update set code=excluded.code returning id`,[workspaceId])).rows[0],membership=(await pool.query<{id:string}>(`insert into workspace_memberships(workspace_id,user_id,role_id,status) values($1,$2,$3,'active') returning id`,[workspaceId,user.id,role.id])).rows[0],session=await createSession(pool,{userId:user.id,securityVersion:1,secret:env.SESSION_SECRET,idleMinutes:30,absoluteHours:24});return{userId:user.id,sessionId:session.id,workspaceId,membershipId:membership.id,role:"admin" as const}}
suite("CUSTOMER-GRAPH-01 backend",()=>{beforeAll(()=>pool.query("select 1"));beforeEach(()=>pool.query("truncate users cascade"));afterAll(()=>pool.end());
  it("commits a domain edit, retained point, governing Audit, Outbox and receipt atomically",async()=>{const f=await fixture(),key=`domain-edit-${randomUUID()}`,requestId=randomUUID(),result=await editCompany(pool,{actor:f.actor,companyId:f.company.id,key,requestId,command:{contractVersion:"company-edit.v1",expectedVersion:f.company.version,displayName:"After",domain:"after.test",responsibleMembershipId:null,responsibleTeamId:null,visibility:"workspace",visibleTeamIds:[]}});expect(result).toMatchObject({version:2,replayed:false});
    const state=(await pool.query(`select c.domain_normalized,c.version,(select count(*)::int from company_domain_points where workspace_id=c.workspace_id and company_id=c.id and lifecycle='archived') archived,(select count(*)::int from company_domain_points where workspace_id=c.workspace_id and company_id=c.id and lifecycle='active' and domain_normalized='after.test') active,(select count(*)::int from audit_events where workspace_id=c.workspace_id and target_id=c.id and action='crm.company.updated') audits,(select count(*)::int from outbox_messages where workspace_id=c.workspace_id and aggregate_id=c.id and topic='crm.company.updated.v1') outbox,(select count(*)::int from idempotency_records where principal_key=$2 and operation='company-edit.v1' and idempotency_key=$3) receipts from companies c where c.workspace_id=$1 and c.id=$4`,[f.actor.workspaceId,`workspace:${f.actor.workspaceId}:membership:${f.actor.membershipId}`,key,f.company.id])).rows[0];expect(state).toMatchObject({domain_normalized:"after.test",version:2,archived:1,active:1,audits:1,outbox:1,receipts:1});
    await expect(editCompany(pool,{actor:f.actor,companyId:f.company.id,key,requestId,command:{contractVersion:"company-edit.v1",expectedVersion:f.company.version,displayName:"After",domain:"after.test",responsibleMembershipId:null,responsibleTeamId:null,visibility:"workspace",visibleTeamIds:[]}})).resolves.toMatchObject({version:2,replayed:true});
  });
  it("does not disclose stale affiliation Company identity when the Company archives during detail assembly",async()=>{const f=await fixture(),operationId=randomUUID(),contact=(await pool.query<{id:string}>(`insert into contacts(workspace_id,display_name,person_name_normalized,normalization_version,status,visibility,governing_operation_id,created_by_membership_id,updated_by_membership_id,authority_contract_version) values($1,'Person','person','customer-graph-v1','active','workspace',$2,$3,$3,'customer-graph-v1') returning id`,[f.actor.workspaceId,operationId,f.actor.membershipId])).rows[0];await pool.query(`insert into contact_company_affiliations(workspace_id,contact_id,company_id,role_code,is_primary,valid_from,governing_operation_id,created_by_membership_id) values($1,$2,$3,'employee',true,now(),$4,$5)`,[f.actor.workspaceId,contact.id,f.company.id,operationId,f.actor.membershipId]);
    const view=await getCustomerGraph(pool,f.actor,"contact",contact.id,randomUUID(),async()=>{await pool.query(`update companies set status='archived',version=version+1,archived_at=now(),archived_by_membership_id=$3,updated_at=now() where workspace_id=$1 and id=$2`,[f.actor.workspaceId,f.company.id,f.actor.membershipId])});expect(view.record.affiliations).toEqual([{companyUnavailable:true}]);expect(JSON.stringify(view)).not.toContain(f.company.id);expect(JSON.stringify(view)).not.toContain("Before");
  });
  it("recomputes Contact disclosure and capabilities after an Owner is downgraded mid-detail",async()=>{const f=await fixture(),operationId=randomUUID(),contact=(await pool.query<{id:string}>(`insert into contacts(workspace_id,display_name,person_name_normalized,first_name,email_display,email_normalized,normalization_version,status,visibility,governing_operation_id,created_by_membership_id,updated_by_membership_id,authority_contract_version) values($1,'Sensitive Person','sensitive person','Sensitive','secret@example.test','secret@example.test','customer-graph-v1','active','workspace',$2,$3,$3,'customer-graph-v1') returning id`,[f.actor.workspaceId,operationId,f.actor.membershipId])).rows[0],memberRole=(await pool.query<{id:string}>(`insert into roles(workspace_id,code,permissions,is_system) values($1,'member','{}',true) on conflict(workspace_id,code) do update set code=excluded.code returning id`,[f.actor.workspaceId])).rows[0];
    const view=await getCustomerGraph(pool,f.actor,"contact",contact.id,randomUUID(),async()=>{await pool.query(`update workspace_memberships set role_id=$3,version=version+1,updated_at=now() where workspace_id=$1 and id=$2`,[f.actor.workspaceId,f.actor.membershipId,memberRole.id])});expect(view.record).toMatchObject({email:null,phone:null,maskedEmail:"s***@example.test",disclosure:{channels:"masked"},capabilities:{canEdit:false,canArchive:false,canManageAffiliations:false,canManageAssignment:false}});expect(JSON.stringify(view)).not.toContain("secret@example.test");expect(view.options).toEqual({responsibleMemberships:[],teams:[]});
  });
  it("fails the whole selected page when a record becomes hidden before serialization",async()=>{const f=await fixture(),member=await memberActor(f.actor.workspaceId);await expect(listCustomerGraph(pool,member,"company",{status:"active",limit:25,bootstrap:false},randomUUID(),async()=>{await pool.query(`update companies set visibility='teams',version=version+1,updated_at=now() where workspace_id=$1 and id=$2`,[f.actor.workspaceId,f.company.id])})).rejects.toMatchObject({code:"resource_not_found",status:404});
  });
  it("fails the whole selected page when current Team access is removed",async()=>{const f=await fixture(),member=await memberActor(f.actor.workspaceId),team=(await pool.query<{id:string}>(`insert into teams(workspace_id,name,name_normalized,status,created_by_membership_id) values($1,'Visible','visible','active',$2) returning id`,[f.actor.workspaceId,f.actor.membershipId])).rows[0];await pool.query(`insert into team_memberships(workspace_id,team_id,workspace_membership_id,created_by_membership_id) values($1,$2,$3,$4)`,[f.actor.workspaceId,team.id,member.membershipId,f.actor.membershipId]);await pool.query(`update companies set visibility='teams',version=version+1,updated_at=now() where workspace_id=$1 and id=$2`,[f.actor.workspaceId,f.company.id]);await pool.query(`insert into company_visible_teams(workspace_id,company_id,team_id,created_by_membership_id) values($1,$2,$3,$4)`,[f.actor.workspaceId,f.company.id,team.id,f.actor.membershipId]);await expect(listCustomerGraph(pool,member,"company",{status:"active",limit:25,bootstrap:false},randomUUID(),async()=>{await pool.query(`delete from team_memberships where workspace_id=$1 and team_id=$2 and workspace_membership_id=$3`,[f.actor.workspaceId,team.id,member.membershipId])})).rejects.toMatchObject({code:"resource_not_found",status:404});
  });
  it("issues create capability from final authority without customer disclosure",async()=>{const f=await fixture(),admin=await adminActor(f.actor.workspaceId),member=await memberActor(f.actor.workspaceId),query={status:"active" as const,limit:25,bootstrap:true};for(const actor of [f.actor,admin])await expect(listCustomerGraph(pool,actor,"company",query,randomUUID())).resolves.toMatchObject({capabilities:{canCreate:true},items:[],nextCursor:null});await expect(listCustomerGraph(pool,member,"contact",query,randomUUID())).resolves.toMatchObject({capabilities:{canCreate:false},items:[],nextCursor:null});const memberRole=(await pool.query<{id:string}>(`select id from roles where workspace_id=$1 and code='member'`,[f.actor.workspaceId])).rows[0];await expect(listCustomerGraph(pool,f.actor,"contact",query,randomUUID(),async()=>{await pool.query(`update workspace_memberships set role_id=$3,version=version+1,updated_at=now() where workspace_id=$1 and id=$2`,[f.actor.workspaceId,f.actor.membershipId,memberRole.id])})).resolves.toMatchObject({capabilities:{canCreate:false},items:[],nextCursor:null});
  });
});
