import React from "react";
import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { DealBoardPage, DealDetailPage, DealFormPage, DealListPage, salesErrorDisposition } from "@/frontend/features/deals";

const routes = [["src/app/crm/deals/page.tsx", "Deals | NexaFlow"], ["src/app/crm/deals/board/page.tsx", "Deal board | NexaFlow"], ["src/app/crm/deals/new/page.tsx", "Add Deal | NexaFlow"], ["src/app/crm/deals/[dealId]/page.tsx", "Deal details | NexaFlow"], ["src/app/crm/deals/[dealId]/edit/page.tsx", "Edit Deal | NexaFlow"]] as const;
describe("DEALS-01 routes and interactions", () => {
  it.each(routes)("keeps %s dynamic and Workspace-scoped", (path, title) => { const source = readFileSync(path, "utf8"); expect(source).toContain('dynamic = "force-dynamic"'); expect(source).toContain(title); expect(source).toContain("crmPageContext("); expect(source).toContain("await pool.end()"); });
  it("renders only truthful loading state before protected data or create authority", () => { const workspaceId = "30000000-0000-4000-8000-000000000001", list = renderToStaticMarkup(<DealListPage workspaceId={workspaceId}/>), board = renderToStaticMarkup(<DealBoardPage workspaceId={workspaceId}/>), detail = renderToStaticMarkup(<DealDetailPage workspaceId={workspaceId} dealId="30000000-0000-4000-8000-000000000002"/>), form = renderToStaticMarkup(<DealFormPage workspaceId={workspaceId}/>); expect(list).toContain("Loading Deals"); expect(board).toContain("Loading Deal board"); expect(detail).toContain("Loading Deal"); expect(form).toContain("Checking permission to add Deal"); expect(form).not.toContain("<form"); expect(`${list}${board}${detail}${form}`).not.toMatch(/Acme|\$248k|example@example/i); });
  it("classifies authority, stale, retry, and new-request outcomes", () => { const error = (code: string, action: "none" | "refetch_deal" | "refetch_pipeline" | "retry_same_request") => ({ code, message: "Safe", retryable: false, reconciliation: { required: action !== "none", action } }) as never; for (const code of ["authentication_required", "permission_required", "resource_not_found"]) expect(salesErrorDisposition(error(code, "none"))).toBe("authority_loss"); expect(salesErrorDisposition(error("stale_version", "refetch_deal"))).toBe("stale"); expect(salesErrorDisposition(error("sales_unavailable", "retry_same_request"))).toBe("retry_same_request"); expect(salesErrorDisposition(error("idempotency_conflict", "none"))).toBe("new_request"); });
  it("encodes sorted repeated Board cursors and clears List-only state", () => { const source = readFileSync("src/frontend/features/deals/components/deals.tsx", "utf8"), boardRoute = readFileSync("src/app/crm/deals/board/page.tsx", "utf8"); expect(source).toContain('endpoint(workspaceId, "deals/board")'); expect(source).toContain('query.append("stageCursor", value)'); expect(source).toContain("localeCompare"); expect(source).not.toContain("JSON.stringify(stageCursors)"); expect(source).toContain("List-only stage drill-down"); expect(source).toContain('lifecycle === "active"'); expect(boardRoute).toContain("stageCursorParams"); });
  it("preserves accessible stage/lifecycle dialogs and complete adverse states", () => { const source = readFileSync("src/frontend/features/deals/components/deals.tsx", "utf8"); expect(source).toContain("showModal()"); expect(source).toContain("onCancel"); expect(source).toContain("restore.current()"); expect(source).toContain("Reload latest"); expect(source).toContain("Changing stage…"); expect(source).toContain("already applied"); expect(source).toContain("already in this stage"); expect(source).toContain("lost-reason-"); expect(source).toContain("form.current?.reset()"); expect(source).not.toContain("window.confirm"); });
  it("keeps Cancel available through async stage loading and refocuses it when detail resolves", () => { const source = readFileSync("src/frontend/features/deals/components/deals.tsx", "utf8"); expect(source).toContain("cancel = useRef<HTMLButtonElement>(null)"); expect(source).toContain("if (open && !loading && !result) cancel.current?.focus()"); expect(source).toContain('<button ref={cancel} type="button"'); expect(source).toContain('{!loading && <Button variant='); });
  it("links every invalid field to a focused summary", () => { const source = readFileSync("src/frontend/features/deals/components/deals.tsx", "utf8"); expect(source).toContain('href={`#${name}`}'); for (const field of ["name", "value", "expectedCloseOn", "stageId", "companyId", "contactIds", "primaryContactId", "responsibleMembershipId", "responsibleTeamId", "visibility", "visibleTeamIds"]) expect(source, field).toContain(`${field}-error`); });
});
