import type { Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { createDb } from "../src/server/db/client";
import { decryptEnvelope, keyedHash } from "../src/server/security/crypto";
import { acceptedResponse, completePasswordReset, loginPassword, registerPasswordUser, requestPasswordReset, verifyEmailToken } from "../src/server/identity/service";
import { claimOutbox, finalizeOutboxFailure, finalizeOutboxSuccess, processOneOutbox } from "../src/server/email/outbox";
import { resolveIdentityContext, revokeAllSessions, revokeCurrentSession } from "../src/server/security/session";

const integration=process.env.RUN_DB_INTEGRATION==="1"?describe:describe.skip;
const connectionString=process.env.DATABASE_URL??"postgres://nexaflow:nexaflow@127.0.0.1:54329/nexaflow";
const config={secret:"integration-secret-at-least-32-characters",appOrigin:"http://127.0.0.1:3000",idleMinutes:30,absoluteHours:24,touchIntervalSeconds:60};
let pool:Pool;
const registration=(email:string,cadence="monthly")=>registerPasswordUser(pool,{email,displayName:"Local User",password:"Local-password-123!",planCode:"growth",cadence,riskKey:`risk-${email}`},config);
async function tokenFromOutbox(topic:string){const result=await pool.query<{payload:{envelope:string}}>("select payload from outbox_messages where topic=$1 order by created_at desc limit 1",[topic]);const email=decryptEnvelope<{text:string}>(result.rows[0].payload.envelope,config.secret);return decodeURIComponent(email.text.split("token=")[1]);}

integration("Slice 2 identity and session foundation",()=>{
  beforeAll(()=>{({pool}=createDb({connectionString}))});
  beforeEach(async()=>{await pool.query("truncate table users, outbox_messages, audit_events, rate_limit_windows cascade")});
  afterAll(async()=>{await pool?.end()});

  it("registers atomically without workspace or trial and stores no raw secret",async()=>{await registration("new@example.test");const counts=await pool.query<{users:string;workspaces:string;onboarding:string;audit:string;outbox:string}>(`select (select count(*) from users) users,(select count(*) from workspaces) workspaces,(select count(*) from onboarding_progress) onboarding,(select count(*) from audit_events) audit,(select count(*) from outbox_messages) outbox`);expect(counts.rows[0]).toEqual({users:"1",workspaces:"0",onboarding:"1",audit:"1",outbox:"1"});const row=await pool.query<{password_hash:string;token_hash:string;payload:unknown}>(`select c.password_hash,t.token_hash,o.payload from identity_credentials c join identity_tokens t on t.user_id=c.user_id cross join outbox_messages o limit 1`);expect(row.rows[0].password_hash).toContain("argon2id");expect(JSON.stringify(row.rows[0])).not.toContain("Local-password-123!");expect(JSON.stringify(row.rows[0].payload)).not.toContain("token=");});

  it("serializes concurrent duplicate registration to one pending user",async()=>{const results=await Promise.all([registration("same@example.test"),registration("same@example.test")]);expect(results).toEqual([acceptedResponse,acceptedResponse]);const count=await pool.query("select count(*) count from users");expect(count.rows[0].count).toBe("1")});

  it("rolls back user, credential, onboarding, audit, and outbox together",async()=>{await expect(registration("rollback@example.test","weekly")).rejects.toMatchObject({code:"23514"});const result=await pool.query(`select (select count(*) from users) users,(select count(*) from audit_events) audits,(select count(*) from outbox_messages) outbox`);expect(result.rows[0]).toEqual({users:"0",audits:"0",outbox:"0"})});

  it("consumes verification tokens once and activates no workspace",async()=>{await registration("verify@example.test");const token=await tokenFromOutbox("identity.email_verification");expect(await verifyEmailToken(pool,token,config)).toEqual({ok:true});expect(await verifyEmailToken(pool,token,config)).toEqual({ok:false,code:"invalid_or_expired"});const result=await pool.query("select u.status,p.current_step,(select count(*) from workspaces) workspaces from users u join onboarding_progress p on p.user_id=u.id");expect(result.rows[0]).toEqual({status:"active",current_step:"workspace",workspaces:"0"})});

  it("returns the same reset-request response for known and unknown accounts",async()=>{await registration("known@example.test");await verifyEmailToken(pool,await tokenFromOutbox("identity.email_verification"),config);expect(await requestPasswordReset(pool,"known@example.test","known-risk",config)).toEqual(acceptedResponse);expect(await requestPasswordReset(pool,"missing@example.test","missing-risk",config)).toEqual(acceptedResponse)});

  it("rotates login sessions and enforces current/all-device revocation and expiry",async()=>{await registration("login@example.test");await verifyEmailToken(pool,await tokenFromOutbox("identity.email_verification"),config);const first=await loginPassword(pool,{email:"login@example.test",password:"Local-password-123!",riskKey:"login-1"},config);expect(first.ok).toBe(true);if(!first.ok)return;const second=await loginPassword(pool,{email:"login@example.test",password:"Local-password-123!",riskKey:"login-2",existingSession:first.sessionToken},config);expect(second.ok).toBe(true);if(!second.ok)return;expect(await resolveIdentityContext(pool,first.sessionToken,config.secret)).toBeNull();expect(await resolveIdentityContext(pool,second.sessionToken,config.secret)).not.toBeNull();await revokeCurrentSession(pool,second.sessionToken,config.secret);expect(await resolveIdentityContext(pool,second.sessionToken,config.secret)).toBeNull();const third=await loginPassword(pool,{email:"login@example.test",password:"Local-password-123!",riskKey:"login-3"},config);if(!third.ok)return;await pool.query("update sessions set idle_expires_at=now()-interval '1 second' where session_hash is not null");expect(await resolveIdentityContext(pool,third.sessionToken,config.secret)).toBeNull();const user=await pool.query("select id from users limit 1");await revokeAllSessions(pool,user.rows[0].id);expect(await resolveIdentityContext(pool,third.sessionToken,config.secret)).toBeNull()});

  it("resets once, revokes existing sessions, and rejects replay",async()=>{await registration("reset@example.test");await verifyEmailToken(pool,await tokenFromOutbox("identity.email_verification"),config);const login=await loginPassword(pool,{email:"reset@example.test",password:"Local-password-123!",riskKey:"reset-login"},config);if(!login.ok)throw new Error("login failed");await requestPasswordReset(pool,"reset@example.test","reset-risk",config);const token=await tokenFromOutbox("identity.password_reset");expect(await completePasswordReset(pool,token,"Changed-password-123!",config)).toEqual({ok:true});expect(await completePasswordReset(pool,token,"Changed-password-123!",config)).toEqual({ok:false,code:"invalid_or_expired"});expect(await resolveIdentityContext(pool,login.sessionToken,config.secret)).toBeNull();expect((await loginPassword(pool,{email:"reset@example.test",password:"Changed-password-123!",riskKey:"new-login"},config)).ok).toBe(true)});

  it("leases outbox messages once under concurrency and marks delivery",async()=>{await registration("mail@example.test");const [a,b]=await Promise.all([claimOutbox(pool,"a"),claimOutbox(pool,"b")]);expect([a,b].filter(Boolean)).toHaveLength(1);await pool.query("update outbox_messages set status='retry',lease_until=null");const sent:string[]=[];expect(await processOneOutbox(pool,{send:async(message)=>{sent.push(message.to);return{messageId:"local-1"}}},config.secret,"worker")).toBe(true);expect(sent).toEqual(["mail@example.test"]);const state=await pool.query("select status,provider_message_id from outbox_messages");expect(state.rows[0]).toEqual({status:"delivered",provider_message_id:"local-1"})});

  it("retries failed outbox delivery and reaches dead letter with sanitized errors",async()=>{await registration("failure@example.test");const failing={send:async()=>{throw new Error("provider secret detail: local delivery unavailable")}};for(let attempt=0;attempt<5;attempt++){await pool.query("update outbox_messages set available_at=now(),lease_until=null where status in ('retry','pending')");expect(await processOneOutbox(pool,failing,config.secret,`worker-${attempt}`)).toBe(true)}const result=await pool.query("select status,attempts,last_error from outbox_messages");expect(result.rows[0]).toEqual({status:"dead_letter",attempts:5,last_error:"delivery_unavailable"})});

  it("enforces network and destination rate-limit dimensions without disclosing existence",async()=>{const replies=[];for(let i=0;i<5;i++)replies.push(await requestPasswordReset(pool,"unknown@example.test",{networkKey:"same-network"},config));expect(replies.every(reply=>JSON.stringify(reply)===JSON.stringify(acceptedResponse))).toBe(true);const rows=await pool.query("select attempts from rate_limit_windows where action='reset_request' order by risk_key_hash");expect(rows.rows).toHaveLength(2);expect(rows.rows.every(row=>row.attempts===5)).toBe(true)});

  it("rejects weak passwords before registration or reset persistence",async()=>{await expect(registerPasswordUser(pool,{email:"weak@example.test",displayName:"Weak",password:"abcdefghijkl",riskKey:"weak"},config)).rejects.toMatchObject({code:"password_policy"});expect((await pool.query("select count(*) count from users")).rows[0].count).toBe("0");await registration("strong@example.test");await verifyEmailToken(pool,await tokenFromOutbox("identity.email_verification"),config);await requestPasswordReset(pool,"strong@example.test","reset",config);const token=await tokenFromOutbox("identity.password_reset");await expect(completePasswordReset(pool,token,"abcdefghijkl",config)).rejects.toMatchObject({code:"password_policy"});expect((await pool.query("select consumed_at from identity_tokens where purpose='password_reset'")).rows[0].consumed_at).toBeNull()});

  it("touches active sessions concurrently, expires idle sessions, and never exceeds absolute expiry",async()=>{await registration("touch@example.test");await verifyEmailToken(pool,await tokenFromOutbox("identity.email_verification"),config);const logged=await loginPassword(pool,{email:"touch@example.test",password:"Local-password-123!",riskKey:"touch"},config);if(!logged.ok)throw new Error("login failed");const hash=keyedHash(logged.sessionToken,config.secret),now=new Date("2026-08-20T20:00:00Z");await pool.query("update sessions set last_seen_at=$2::timestamptz-interval '2 minutes',idle_expires_at=$2::timestamptz+interval '5 minutes',absolute_expires_at=$2::timestamptz+interval '2 hours' where session_hash=$1",[hash,now]);const contexts=await Promise.all(Array.from({length:5},()=>resolveIdentityContext(pool,logged.sessionToken,config.secret,now,{idleMinutes:30,touchIntervalSeconds:60})));expect(contexts.every(Boolean)).toBe(true);let row=(await pool.query("select last_seen_at,idle_expires_at,absolute_expires_at from sessions where session_hash=$1",[hash])).rows[0];expect(row.last_seen_at.toISOString()).toBe(now.toISOString());expect(row.idle_expires_at.toISOString()).toBe("2026-08-20T20:30:00.000Z");await pool.query("update sessions set last_seen_at=$2::timestamptz-interval '2 minutes',idle_expires_at=$2::timestamptz+interval '1 minute',absolute_expires_at=$2::timestamptz+interval '5 minutes' where session_hash=$1",[hash,now]);expect(await resolveIdentityContext(pool,logged.sessionToken,config.secret,now,{idleMinutes:30,touchIntervalSeconds:60})).not.toBeNull();row=(await pool.query("select idle_expires_at,absolute_expires_at from sessions where session_hash=$1",[hash])).rows[0];expect(row.idle_expires_at.toISOString()).toBe(row.absolute_expires_at.toISOString());await pool.query("update sessions set idle_expires_at=$2::timestamptz-interval '1 second' where session_hash=$1",[hash,now]);expect(await resolveIdentityContext(pool,logged.sessionToken,config.secret,now,{idleMinutes:30,touchIntervalSeconds:60})).toBeNull()});

  it("denies suspended users an authenticated request context",async()=>{await registration("suspended@example.test");await verifyEmailToken(pool,await tokenFromOutbox("identity.email_verification"),config);const logged=await loginPassword(pool,{email:"suspended@example.test",password:"Local-password-123!",riskKey:"suspended"},config);if(!logged.ok)throw new Error("login failed");await pool.query("update users set status='suspended'");expect(await resolveIdentityContext(pool,logged.sessionToken,config.secret)).toBeNull()});

  it("fences stale outbox workers after lease expiry and reclaim",async()=>{await registration("fence@example.test");const first=await claimOutbox(pool,"worker-a",1);expect(first).not.toBeNull();await pool.query("update outbox_messages set lease_until=now()-interval '1 second'");const second=await claimOutbox(pool,"worker-b",30);expect(second).not.toBeNull();expect(second!.lease_generation).toBe(first!.lease_generation+1);expect(await finalizeOutboxSuccess(pool,first!,"stale-provider-id")).toBe(false);expect(await finalizeOutboxFailure(pool,first!,new Error("secret provider detail"))).toBe(false);expect(await finalizeOutboxSuccess(pool,second!,"winner-provider-id")).toBe(true);const row=(await pool.query("select status,provider_message_id,provider_idempotency_key,lease_owner from outbox_messages")).rows[0];expect(row.status).toBe("delivered");expect(row.provider_message_id).toBe("winner-provider-id");expect(row.provider_idempotency_key).toBeTruthy();expect(row.lease_owner).toBeNull()});
});
