import{existsSync,readFileSync,readdirSync,statSync}from"node:fs";
import{dirname,join,normalize,relative,resolve}from"node:path";
import{describe,expect,it}from"vitest";
import{sourceCategories,socialPlatforms}from"@/frontend/features/leads/contracts/lead-intake.contracts";
import{decisionFromCandidate}from"@/frontend/features/identity-review/contracts/identity-review.contracts";
import{reviewDetailFixture}from"@/frontend/features/identity-review/testing/identity-review.fixtures";

function files(root:string):string[]{return readdirSync(root).flatMap(name=>{const path=join(root,name);return statSync(path).isDirectory()?files(path):[path]})}
const root="src/frontend",featureRoot=`${root}/features`,frontendFiles=files(root).filter(path=>/\.[cm]?[jt]sx?$/.test(path));
const runtimeImports=/(?:import|export)\s*(?!type\b)(?:[^"']*?\bfrom\s*)?["']([^"']+)["']|require\s*\(\s*["']([^"']+)["']/g;
const allImports=/(?:import|export)\s*(?:type\s*)?(?:[^"']*?\bfrom\s*)?["']([^"']+)["']/g;
function imports(source:string,types=false){return[...source.matchAll(types?allImports:runtimeImports)].map(match=>match[1]??match[2])}
function resolveSource(from:string,specifier:string){if(!specifier.startsWith(".")&&!specifier.startsWith("@/"))return;const base=specifier.startsWith("@/")?join("src",specifier.slice(2)):resolve(dirname(from),specifier);for(const candidate of[base,`${base}.ts`,`${base}.tsx`,join(base,"index.ts"),join(base,"index.tsx")])if(existsSync(candidate)&&statSync(candidate).isFile())return normalize(relative(process.cwd(),candidate))}
function graphFor(sources:Record<string,string>,types=false){return Object.fromEntries(Object.entries(sources).map(([path,source])=>[path,imports(source,types).map(item=>{const actual=resolveSource(path,item);if(actual)return actual;if(item.startsWith(".")){const base=normalize(join(dirname(path),item));return[base,`${base}.ts`,`${base}.tsx`,join(base,"index.ts")].find(candidate=>candidate in sources)}}).filter((item):item is string=>Boolean(item))]))}
function hasCycle(graph:Record<string,string[]>){const active=new Set<string>(),done=new Set<string>();const visit=(node:string):boolean=>active.has(node)||(!done.has(node)&&(()=>{active.add(node);const found=(graph[node]??[]).some(visit);active.delete(node);done.add(node);return found})());return Object.keys(graph).some(visit)}
function reachable(graph:Record<string,string[]>,start:string){const found=new Set<string>(),pending=[start];while(pending.length)for(const item of graph[pending.pop()!]??[])if(!found.has(item)){found.add(item);pending.push(item)}return found}
function privateCrossFeature(path:string,source:string){const owner=path.match(/frontend\/features\/([^/]+)/)?.[1];return imports(source,true).filter(specifier=>{const match=specifier.match(/^@\/frontend\/features\/([^/]+)(?:\/(.+))?$/);return match&&match[1]!==owner&&Boolean(match[2])})}
function routeDeepImports(source:string){return imports(source,true).filter(specifier=>/^@\/frontend\/features\/[^/]+\/(?!server$)/.test(specifier))}
function publicEntryViolations(source:string){return[...([...source.matchAll(/export\s*\*/g)].map(()=>"wildcard export")),...imports(source,true).filter(target=>!/^\.\/(?:components|contracts|server)\/[^/]+$/.test(target))]}
function unsafeProductionFixture(path:string,source:string){return!path.includes("/testing/")&&(imports(source,true).some(item=>/(?:^|\/)testing(?:\/|$)|(?:^|\/)fixtures?(?:[./]|$)/i.test(item))||/\b(?:fixture|mock)(?:Email|Phone|Password|Secret)\b/.test(source))}

describe("P1A frontend authority and view-model boundaries",()=>{
 it("blocks transitive browser reachability to server, backend, database, and secrets",()=>{const sources=Object.fromEntries(frontendFiles.map(path=>[path,readFileSync(path,"utf8")])),graph=graphFor(sources);for(const path of frontendFiles.filter(path=>/^\s*["']use client["']/m.test(sources[path])))for(const dependency of[path,...reachable(graph,path)])expect(sources[dependency]??"",`${path} reaches ${dependency}`).not.toMatch(/(?:from\s*["'](?:@\/(?:backend|server)\/|pg["'])|import\s*["']server-only["']|process\.env|@\/server\/db|\b(?:DATABASE_URL|API_SECRET|PRIVATE_KEY)\b)/);const negative={"client.tsx":`"use client"; import {x} from "./bridge"`,"bridge.ts":`import {db} from "@/server/db/client"`};expect([...reachable(graphFor(negative),"client.tsx")]).toContain("bridge.ts");expect(negative["bridge.ts"]).toMatch(/@\/server\/db/)});
 it("blocks private cross-feature imports and cycles with negative fixtures",()=>{const sources=Object.fromEntries(frontendFiles.map(path=>[path,readFileSync(path,"utf8")]));for(const[path,source]of Object.entries(sources))expect(privateCrossFeature(path,source),path).toEqual([]);expect(privateCrossFeature("src/frontend/features/leads/x.ts",`import{x}from"@/frontend/features/identity-review/contracts/x"`)).not.toEqual([]);expect(hasCycle(graphFor(sources,true))).toBe(false);expect(hasCycle({"a.ts":["b.ts"],"b.ts":["a.ts"]})).toBe(true)});
 it("keeps routes on public feature entries and rejects deep route imports",()=>{for(const path of files("src/app/crm").filter(path=>/(?:page|layout)\.tsx$/.test(path)))expect(routeDeepImports(readFileSync(path,"utf8")),path).toEqual([]);expect(routeDeepImports(`import{Form}from"@/frontend/features/leads/components/form"`)).toHaveLength(1)});
 it("locks public entries/manifests and rejects nested adapters and unsafe fixtures",()=>{for(const feature of readdirSync(featureRoot).filter(name=>statSync(join(featureRoot,name)).isDirectory())){const entry=`${featureRoot}/${feature}/index.ts`,readme=`${featureRoot}/${feature}/README.md`;expect(statSync(entry).isFile()).toBe(true);expect(readFileSync(readme,"utf8"),readme).toMatch(/Public entry:\s*`index\.ts`/);expect(publicEntryViolations(readFileSync(entry,"utf8")),entry).toEqual([])}expect(publicEntryViolations(`export * from "./testing/private"`)).not.toEqual([]);expect(frontendFiles.filter(path=>/\/(?:components|contracts|server)\/.+\/(?:adapters?|ports?)\//.test(path))).toEqual([]);expect("src/frontend/features/leads/server/nested/adapters/http.ts").toMatch(/\/(?:components|contracts|server)\/.+\/(?:adapters?|ports?)\//);for(const path of frontendFiles)expect(unsafeProductionFixture(path,readFileSync(path,"utf8")),path).toBe(false);expect(unsafeProductionFixture("src/frontend/features/leads/components/x.ts",`import{lead}from"../testing/lead.fixtures"`)).toBe(true)});
 it("locks wire identities and rejects drift fixtures",()=>{const fixture=JSON.parse(readFileSync("tests/fixtures/p1a-contract-v1.json","utf8"))as Record<string,string[]>,registered=new Set([...fixture.operations,...fixture.queries]),contracts=frontendFiles.filter(path=>path.includes("/contracts/")).map(path=>readFileSync(path,"utf8")).join("\n"),identities=[...contracts.matchAll(/["'](lead-(?:inquiry-intake|identity-review-(?:decision|detail|queue))\.v\d+)["']/g)].map(match=>match[1]);for(const identity of identities)expect(registered.has(identity),identity).toBe(true);for(const identity of registered)expect(identities,identity).toContain(identity);expect(registered.has("lead-identity-review-detail.v999")).toBe(false)});
 it("locks registries and safe candidate decisions",()=>{expect(sourceCategories.map(([id])=>id)).toEqual(["website","referral","outbound","event","partner","social_media","import","manual","other"]);expect(socialPlatforms.map(([id])=>id)).toEqual(["tiktok","instagram","facebook","linkedin","x","youtube","other_social"]);const candidate=reviewDetailFixture.candidates[0];expect(candidate.maskedEmail).toContain("***");expect(candidate).not.toHaveProperty("email");expect(decisionFromCandidate(candidate)).toEqual({action:"link",candidateId:candidate.candidateId,targetId:candidate.targetId,expectedTargetVersion:1})});
});
