import{describe,expect,it}from"vitest";
import{createManualIntakeBootstrap}from"@/frontend/features/leads/contracts/lead-intake.contracts";
import{buildDecisionCommand,isAuthorityLoss,linkChoiceAvailable,reviewErrorDisposition,safeChoiceSummary}from"@/frontend/features/identity-review";
import{intakeRequestIdentityDisposition}from"@/frontend/features/leads";
import{reviewDetailFixture}from"@/frontend/features/identity-review/testing/identity-review.fixtures";
import{LeadIntakeError}from"@/backend/modules/leads/contracts/lead-inquiry-intake.contract";
import{leadIntakeFailure}from"@/backend/modules/leads/presentation/lead-intake.http";
import{errorEnvelopeSchema}from"@/frontend/shared/contracts/p1a-transport";

describe("P1A frontend interaction decisions",()=>{
 it("creates request-scoped deterministic intake timestamps",()=>{const first=createManualIntakeBootstrap(()=>new Date("2026-08-25T10:00:00.000Z")),second=createManualIntakeBootstrap(()=>new Date("2026-08-25T10:01:00.000Z"));expect(first.receivedAt).not.toBe(second.receivedAt);expect(first.receivedAt).toBe("2026-08-25T10:00:00.000Z")});
 it("emits a Hold-only body even for a stale server view",()=>{const stale={...reviewDetailFixture,candidates:[],candidateSummary:{strong:0,supplementary:0,probable:0},capabilities:{canCreateContact:false,canCreateCompany:false,canLinkContact:false,canLinkCompany:false,canDismiss:false,canHold:true,canResolve:false},reconciliation:{status:"stale"as const,retryable:true as const,action:"refresh_identity_review"as const}};expect(buildDecisionCommand(stale,"hold","create","dismiss")).toEqual({contractVersion:"lead-identity-review-decision.v1",expectedLeadVersion:1,expectedReviewVersion:1,expectedIntakeVersion:1,outcome:"hold"})});
 it("requires both dimension and candidate link authority",()=>{const candidate=reviewDetailFixture.candidates[0],denied={...candidate,canLink:false};expect(linkChoiceAvailable(reviewDetailFixture,"contact",candidate)).toBe(true);expect(linkChoiceAvailable(reviewDetailFixture,"contact",denied)).toBe(false);expect(buildDecisionCommand({...reviewDetailFixture,candidates:[denied]},"resolve",`link:${denied.candidateId}`,"dismiss")).toBeNull()});
 it("never uses command encodings in human decision copy",()=>{const candidate=reviewDetailFixture.candidates[0],summary=safeChoiceSummary(`link:${candidate.candidateId}`,reviewDetailFixture.candidates);expect(summary).toContain("Link contact");expect(summary).not.toContain(candidate.candidateId);expect(summary).not.toContain(candidate.targetId);expect(summary).not.toContain("link:")});
 it("fails closed for every authority-loss error",()=>{expect(["authentication_required","permission_required","resource_not_found"].every(isAuthorityLoss)).toBe(true);expect(isAuthorityLoss("intake_unavailable")).toBe(false)});
 it("binds every backend stable error to one deterministic UI reconciliation behavior",async()=>{const statuses={authentication_required:401,permission_required:403,resource_not_found:404,validation_failed:400,unsupported_contract_version:400,source_platform_required:400,source_platform_not_allowed:400,invalid_source_category:400,invalid_source_platform:400,invalid_source_medium:400,source_detail_too_large:400,idempotency_conflict:409,stale_version:409,invalid_match_decision:409,assignment_unavailable:409,rate_limited:429,intake_unavailable:503,unexpected_error:500}as const;for(const[code,status]of Object.entries(statuses)){const payload=await leadIntakeFailure(new LeadIntakeError(code as keyof typeof statuses,status),"30000000-0000-4000-8000-000000000001").json(),error=errorEnvelopeSchema.parse(payload).error,expected=["authentication_required","permission_required","resource_not_found"].includes(code)?"authority_loss":error.reconciliation.action==="refetch_identity_review"?"refetch":error.reconciliation.action==="retry_same_request"?"retry_same_request":"new_request";expect(reviewErrorDisposition(error),code).toBe(expected);expect(intakeRequestIdentityDisposition(error),code).toBe(error.reconciliation.action==="retry_same_request"?"preserve":"rotate")}});
 it("constructs every permitted atomic Contact and Company outcome",()=>{const contact=reviewDetailFixture.candidates[0],company={...contact,candidateId:"30000000-0000-4000-8000-000000000004",targetId:"30000000-0000-4000-8000-000000000005",targetType:"company"as const,displayName:"Example Company",maskedEmail:null,maskedPhone:null,companyName:"Example Company",evidenceKind:"name_company"as const,evidenceStrength:"probable"as const},detail={...reviewDetailFixture,candidates:[contact,company],candidateSummary:{strong:1,supplementary:0,probable:1},capabilities:{...reviewDetailFixture.capabilities,canLinkCompany:true}};for(const contactChoice of["create","dismiss",`link:${contact.candidateId}`]as const)for(const companyChoice of["create","dismiss",`link:${company.candidateId}`]as const){const command=buildDecisionCommand(detail,"resolve",contactChoice,companyChoice);expect(command?.outcome).toBe("resolve");expect(command).toHaveProperty("contact");expect(command).toHaveProperty("company")}});
 it("honours Owner/Admin and Member capability matrices without deriving role",()=>{const candidate=reviewDetailFixture.candidates[0],owner={...reviewDetailFixture,capabilities:{...reviewDetailFixture.capabilities,canLinkContact:true}},member={...reviewDetailFixture,capabilities:{...reviewDetailFixture.capabilities,canLinkContact:false,canLinkCompany:false},candidates:[{...candidate,canLink:false}]};expect(linkChoiceAvailable(owner,"contact",candidate)).toBe(true);expect(linkChoiceAvailable(member,"contact",member.candidates[0])).toBe(false);expect(buildDecisionCommand(member,"resolve","create","dismiss")?.outcome).toBe("resolve")});
});
