export { errorEnvelopeSchema, intakeResultSchema, intakeSuccessEnvelopeSchema, leadInquiryIntakeCommandV1Schema,
  type ErrorEnvelope, type IntakeResult, type LeadInquiryIntakeCommandV1, type P1AError, type SocialPlatform,
  type SourceCategory, type SourceMedium } from "@/frontend/shared/contracts/p1a-transport";
import type { SocialPlatform, SourceCategory } from "@/frontend/shared/contracts/p1a-transport";
import { parsePhoneNumberFromString } from "libphonenumber-js/max";
export const phoneInputHelp="Enter a 10-digit Canada/US number, an 11-digit number beginning with 1, or an international number beginning with +. Spaces, parentheses, hyphens and dots are accepted.";
export const phoneInputError="Enter a valid phone number in one of the supported formats.";
export function phoneGuidanceIssue(value:string,country?:"CA"|"US"){const display=value.normalize("NFKC").trim();if(!display)return null;if(/[\p{Cc}\p{Cf}]/u.test(display)||/(?:\bext\b|[x#;,])/iu.test(display)||!/^\+?[0-9 ().-]+$/u.test(display)||display.slice(1).includes("+"))return phoneInputError;const digits=display.replace(/[ ().-]/g,"");if(display.startsWith("+")){const international=digits.slice(1),normalized=`+${international}`;if(!/^[1-9]\d{7,14}$/.test(international))return phoneInputError;const parsed=parsePhoneNumberFromString(normalized);return parsed&&parsed.number===normalized&&parsed.countryCallingCode?null:phoneInputError}if(!country||!/^\d+$/.test(digits)||digits.length===11&&!digits.startsWith("1")||digits.length!==10&&!(digits.length===11&&digits.startsWith("1")))return phoneInputError;return null}
export function createManualIntakeBootstrap(now:()=>Date=()=>new Date()){return{intakeChannel:"manual"as const,receivedAt:now().toISOString()}}
export const sourceCategories:[SourceCategory,string][]=[["website","Website"],["referral","Referral"],["outbound","Outbound"],["event","Event"],["partner","Partner"],["social_media","Social media"],["import","Import"],["manual","Manual"],["other","Other"]];
export const socialPlatforms:[SocialPlatform,string][]=[["tiktok","TikTok"],["instagram","Instagram"],["facebook","Facebook"],["linkedin","LinkedIn"],["x","X"],["youtube","YouTube"],["other_social","Other social"]];
