import type{P1AError}from"@/frontend/features/leads";
export type Capabilities={canCreateContact:boolean;canCreateCompany:boolean;canLinkContact:boolean;canLinkCompany:boolean;canDismiss:boolean;canHold:boolean;canResolve:boolean};
export type Candidate={candidateId:string;targetType:"contact"|"company";targetId:string;targetVersion:number;expectedTargetVersion:number;displayName:string;maskedEmail:string|null;maskedPhone:string|null;companyName?:string;evidenceKind:"email"|"phone"|"name_company";evidenceStrength:"strong"|"supplementary"|"probable";canLink:boolean};
export type Reconciliation={status:"current"|"stale";retryable:boolean;action:"none"|"refresh_identity_review"};
export type ReviewDetail={contractVersion:"lead-identity-review-detail.v1";reviewId:string;leadId:string;requestId:string;reviewVersion:number;leadVersion:number;intakeVersion:number;lead:{displayName:string;maskedEmail:string|null;maskedPhone:string|null;companyName:string|null;lifecycle:"new"|"working"|"qualified"|"disqualified"|"converted";receivedAt:string};originalAttribution:{sourceCategory:string;sourcePlatform:string|null;sourceMedium:string;sourceDetail:Record<string,string>;campaignContext:Record<string,string>;attributionContractVersion:string;intakeChannel:"manual"};assignment:{responsibleMembershipId:string|null;responsibleTeamId:string|null;visibility:"workspace"|"teams"};capabilities:Capabilities;candidateSummary:{strong:number;supplementary:number;probable:number};reconciliation:Reconciliation;candidates:Candidate[];nextView:{kind:"identity_review_detail";leadId:string;reviewId:string}};
export type QueueItem={reviewId:string;leadId:string;lead:{displayName:string;companyName:string|null;receivedAt:string};originalAttribution:{sourceCategory:string;sourcePlatform:string|null;sourceMedium:string;intakeChannel:"manual"};assignment:{responsibleMembershipId:string|null;responsibleTeamId:string|null;visibility:string};versions:{lead:number;review:number;intake:number};candidateSummary:{strong:number;supplementary:number;probable:number};capabilities:Capabilities;reconciliation:Reconciliation;updatedAt:string;nextView:{kind:"identity_review_detail";leadId:string;reviewId:string}};
export type ReviewQueue={contractVersion:"lead-identity-review-queue.v1";requestId:string;items:QueueItem[];nextCursor:string|null};
export type DimensionDecision={action:"dismiss"}|{action:"create"}|{action:"link";candidateId:string;targetId:string;expectedTargetVersion:number};
export type DecisionCommand={contractVersion:"lead-identity-review-decision.v1";expectedLeadVersion:number;expectedReviewVersion:number;expectedIntakeVersion:number}&({outcome:"hold";reasonCode?:string}|{outcome:"resolve";contact:DimensionDecision;company:DimensionDecision;reasonCode?:string});
export type DecisionResult={contractVersion:"lead-identity-review-decision-result.v1";outcome:"hold"|"resolve";disposition:"held_for_review"|"resolved"|"replayed";reviewId:string;leadId:string;contactId:string|null;companyId:string|null;leadVersion:number;reviewVersion:number;replayed:boolean;requestId:string;nextView:{kind:"identity_review_detail";leadId:string;reviewId:string}|{kind:"identity_review_queue"}};
export type ReviewErrorEnvelope={error:P1AError;requestId:string;nextView?:{kind:"identity_review_detail";leadId:string}};
export function decisionFromCandidate(candidate:Candidate):DimensionDecision{return{action:"link",candidateId:candidate.candidateId,targetId:candidate.targetId,expectedTargetVersion:candidate.expectedTargetVersion}}
