import type {Pool} from "pg";
import {writeAudit} from "../security/audit";
import {TenantAdminError,type TenantContext} from "./permissions";

const allowedReasons=new Set(["permission_required","recent_auth_required","invalid_target","invalid_role","invalid_team","email_mismatch","invitation_expired","invitation_revoked","invitation_consumed","seat_limit_reached","stale_version","last_owner","rate_limited","idempotency_conflict","mutation_failed","authentication_required","password_credential_required","invalid_credentials","password_policy"]);
function reason(error:unknown){const code=error instanceof TenantAdminError?error.code:(error&&typeof error==="object"&&"code" in error&&typeof error.code==="string"?error.code:undefined);if(!code)return"mutation_failed";const map:Record<string,string>={resource_not_found:"invalid_target",validation_failed:"invalid_target",invitation_invalid:"invalid_target",team_exists:"invalid_target",owner_transfer_required:"last_owner"},value=map[code]??code;return allowedReasons.has(value)?value:"mutation_failed"}

type DenialInput={context?:TenantContext;userId?:string;sessionId?:string;action:string;targetType:string;targetId?:string;requestId?:string;correlationId?:string;error:unknown};
export async function safeDenialAudit(pool:Pool,input:DenialInput){const client=await pool.connect();try{await client.query("begin");let workspaceId:string|undefined,actorMembershipId:string|undefined,actorUserId=input.userId,sessionId=input.sessionId;if(input.context){const verified=(await client.query<{workspace_id:string;id:string;user_id:string}>(`select m.workspace_id,m.id,m.user_id from workspace_memberships m join roles r on r.id=m.role_id and r.workspace_id=m.workspace_id where m.id=$1 and m.user_id=$2 and m.workspace_id=$3 and m.status='active'`,[input.context.membershipId,input.context.userId,input.context.workspaceId])).rows[0];if(verified){workspaceId=verified.workspace_id;actorMembershipId=verified.id;actorUserId=verified.user_id;sessionId=input.context.sessionId}}await writeAudit(client,{workspaceId,actorMembershipId,actorUserId,sessionId,action:input.action,targetType:input.targetType,targetId:workspaceId?input.targetId:undefined,outcome:"denied",reasonCode:reason(input.error),requestId:input.requestId,correlationId:input.correlationId,metadata:{operation:"tenant_admin_denial"}});await client.query("commit")}catch{await client.query("rollback")}finally{client.release()}}
export async function withDenialAudit<T>(pool:Pool,input:Omit<DenialInput,"error">,work:()=>Promise<T>){try{return await work()}catch(error){await safeDenialAudit(pool,{...input,error});throw error}}
