import{NextResponse}from"next/server";import type{Pool}from"pg";import{getServerEnv}from"../env";import{localDatabase,mutationGuard,requestRiskContext,sessionToken}from"../http";import{consumeRateLimitDimensions}from"../security/rate-limit";import{resolveIdentityContext}from"../security/session";import{resolveTenantContext,TenantAdminError,type TenantContext}from"./permissions";import{safeDenialAudit}from"./denial";
import{selectableWorkspaces}from"../workspaces/selection";
export const requestId=()=>crypto.randomUUID();
export function success(data:unknown,status=200,id=requestId()){return NextResponse.json({data,requestId:id},{status})}
export function failure(error:unknown,id=requestId()){const known=error instanceof TenantAdminError?error:new TenantAdminError("unexpected_error",500);return NextResponse.json({error:{code:known.code,...(known.safe?{resource:known.safe}: {})},requestId:id},{status:known.status})}
export function idempotencyKey(request:Request){const value=request.headers.get("idempotency-key");if(!value||value.length<16||value.length>128||!/^[\x20-\x7e]+$/.test(value))throw new TenantAdminError("validation_failed",400);return value}
export async function identity(pool:Pool,request:Request){const env=getServerEnv(),value=await resolveIdentityContext(pool,sessionToken(request),env.SESSION_SECRET,new Date(),{idleMinutes:env.SESSION_IDLE_MINUTES,touchIntervalSeconds:env.SESSION_TOUCH_INTERVAL_SECONDS});if(!value)throw new TenantAdminError("authentication_required",401);return value}
export async function tenant(pool:Pool,request:Request,workspaceId:string){const value=await identity(pool,request);let selected=value.activeWorkspaceId??null;if(!selected){const options=await selectableWorkspaces(pool,{...value,activeWorkspaceId:null});selected=options.find(option=>option.current)?.id??null}if(!selected||selected!==workspaceId)throw new TenantAdminError("resource_not_found",404);const context=await resolveTenantContext(pool,{...value,workspaceId:selected});if(!context)throw new TenantAdminError("resource_not_found",404);return context}
export async function enforceTenantRate(pool:Pool,request:Request,action:"invite_create"|"invite_resend"|"invite_accept"|"invite_revoke"|"member_change"|"team_change"|"recent_auth",context:{userId:string;membershipId?:string;workspaceId?:string},destination?:string){const env=getServerEnv(),network=requestRiskContext(request).networkKey,dimensions=[`actor:${context.membershipId??context.userId}`,...(context.workspaceId?[`workspace:${context.workspaceId}`]:[]),`network:${network}`,...(destination?[`destination:${destination.trim().toLowerCase()}`]:[])],allowed=await consumeRateLimitDimensions(pool,dimensions.map(riskKey=>({action,riskKey,limit:action==="recent_auth"?5:30,windowSeconds:60,secret:env.SESSION_SECRET})));if(!allowed)throw new TenantAdminError("rate_limited",429)}

export async function auditedMutationGuard(request:Request,input:{action:string;targetType:string}){const blocked=mutationGuard(request);if(!blocked)return null;const{pool}=localDatabase();try{let actor:{userId:string;sessionId:string}|undefined;try{actor=await identity(pool,request)}catch{}if(actor)await safeDenialAudit(pool,{userId:actor.userId,sessionId:actor.sessionId,action:input.action,targetType:input.targetType,error:new TenantAdminError("permission_required",403)});return blocked}finally{await pool.end()}}

export async function auditedFailure(pool:Pool,request:Request,error:unknown,input:{action:string;targetType:string;targetId?:string;context?:TenantContext;correlationId?:string}){const id=requestId();let actor=input.context?{userId:input.context.userId,sessionId:input.context.sessionId}:undefined;if(!actor)try{actor=await identity(pool,request)}catch{}await safeDenialAudit(pool,{context:input.context,userId:actor?.userId,sessionId:actor?.sessionId,action:input.action,targetType:input.targetType,targetId:input.targetId,requestId:id,correlationId:input.correlationId,error});return failure(error,id)}
