import Link from "next/link";
import { CrmShell } from "../crm-shell";
import { crmPageContext } from "@/server/crm/page";
import { CrmHomeError, crmHome, type CrmHomeModel, type CrmHomeRawFilters } from "@/server/crm/home";
import { CRM_HOME_DEMO_PREVIEW } from "./demo";
import { crmLeadHref, hasCrmHomeFilters } from "@/server/crm/home-links";
import { ActionLink } from "@/frontend/design-system";

export const dynamic="force-dynamic";
export const metadata={title:"CRM home | NexaFlow"};

function DashboardError({code}:{code:CrmHomeError["code"]}){const invalid=code==="invalid_filter",missing=code==="resource_not_found";return <section className="admin-content crm-home" aria-labelledby="crm-home-title"><p className="eyebrow">Local CRM</p><h1 id="crm-home-title">CRM home</h1><div className="alert error" role="alert"><div><b>{invalid?"Review the dashboard filters and try again.":missing?"This dashboard view is unavailable.":"We couldn’t load your CRM overview. Try again."}</b><p>No workspace metrics or sample previews are shown while live data is unavailable.</p></div></div><div className="dashboard-actions">{invalid||missing?<Link className="primary link-button" href="/crm/home">Clear filters</Link>:<Link className="primary link-button" href="/crm/home">Try again</Link>}<Link className="secondary link-button" href="/crm">Go to leads</Link></div></section>}

function FilterForm({model}:{model:CrmHomeModel}){const{filters,options,actor}=model;return <form className="dashboard-filters" action="/crm/home" aria-label="Filter CRM snapshot"><label>Status<select name="status" defaultValue={filters.status}><option value="all">All outcomes</option><option value="open">Open</option><option value="won">Won</option><option value="lost">Lost</option></select></label><label>Stage<select name="stage" defaultValue={filters.stage}><option value="all">All stages</option>{options.stages.map(option=><option key={option.id} value={option.id}>{option.label}{option.archived?" — Archived":""}</option>)}</select></label><label>Owner<select name="owner" defaultValue={filters.owner}><option value="all">All owners</option><option value="mine">Mine</option>{options.owners.filter(option=>option.id!==actor.membershipId).map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><label>Team<select name="team" defaultValue={filters.team}><option value="all">All permitted teams</option>{options.teams.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><label>Created<select name="period" defaultValue={filters.period}><option value="all">Any time</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></label><div className="dashboard-filter-actions"><button className="primary">Apply filters</button>{hasCrmHomeFilters(filters)&&<Link className="secondary link-button" href="/crm/home">Clear filters</Link>}</div></form>}

function LiveDashboard({model}:{model:CrmHomeModel}){const max=Math.max(1,...model.pipeline.map(stage=>stage.count)),hasFilters=hasCrmHomeFilters(model.filters),early=model.pipeline.find(stage=>!stage.archived);return <>
  <section className="dashboard-welcome" aria-labelledby="welcome-title"><div><span className="live-badge">Live workspace data</span><p className="eyebrow">{model.workspace.name}</p><h2 id="welcome-title">Welcome back. Let’s move customer work forward.</h2><p>Your dashboard reflects only the Leads and activity you are authorized to access.</p><div className="dashboard-actions"><ActionLink variant="primary" href="/crm/leads/new">Add lead</ActionLink><ActionLink href="/crm">View leads</ActionLink></div></div><div className="welcome-stat" aria-label={`${model.summary.open} open leads`}><strong>{model.summary.open}</strong><span>open leads</span></div></section>
  <FilterForm model={model}/>{model.filters.period!=="all"&&<p className="filter-context">Leads created in the last {model.filters.period.replace("d","")} days.</p>}
  <p className="sr-only" aria-live="polite">{model.summary.visible} visible leads match this dashboard view.</p>
  <section className="dashboard-section" aria-labelledby="snapshot-title"><div className="dashboard-section-heading"><div><p className="eyebrow">Live workspace data</p><h2 id="snapshot-title">CRM snapshot</h2></div><p>Generated <time dateTime={model.generatedAt}>{new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(new Date(model.generatedAt))} UTC</time></p></div>
    <div className="kpi-grid"><Link href={crmLeadHref(model.filters)} className="kpi-card"><span>Visible leads</span><strong>{model.summary.visible}</strong><small>Authorized current population</small></Link><Link href={crmLeadHref(model.filters,{status:"open"})} className="kpi-card"><span>Open</span><strong>{model.summary.open}</strong><small>Current lead outcome</small></Link><Link href={crmLeadHref(model.filters,{status:"won"})} className="kpi-card"><span>Won</span><strong>{model.summary.won}</strong><small>Lead outcome, not revenue</small></Link><Link href={crmLeadHref(model.filters,{status:"lost"})} className="kpi-card"><span>Lost</span><strong>{model.summary.lost}</strong><small>Lead outcome, not conversion</small></Link></div>
    {model.summary.visible===0?<div className="empty dashboard-empty"><h3>{hasFilters?"No leads match these filters.":"No leads to summarize yet."}</h3><p>{hasFilters?"Clear filters to return to the full authorized snapshot.":"Add a lead to begin tracking customer work."}</p>{hasFilters?<Link className="secondary link-button" href="/crm/home">Clear filters</Link>:<Link className="primary link-button" href="/crm/leads/new">Add lead</Link>}</div>:null}
    <div className="dashboard-two-column"><section className="dashboard-card" aria-labelledby="pipeline-health"><div className="card-heading"><div><p className="eyebrow">Current snapshot</p><h3 id="pipeline-health">Pipeline health</h3></div><Link href="/crm/pipeline">Open pipeline</Link></div><ul className="distribution-list">{model.pipeline.map(stage=><li key={stage.stageId}><div><span>{stage.name}{stage.archived?" (Archived)":""}</span><b>{stage.count}</b></div><span className="metric-track" aria-hidden="true"><span style={{width:`${Math.round(stage.count/max*100)}%`}}/></span></li>)}</ul></section>
      <section className="dashboard-card" aria-labelledby="attention-title"><div className="card-heading"><div><p className="eyebrow">Live signals</p><h3 id="attention-title">Needs attention</h3></div></div><ul className="attention-list"><li><div><strong>{model.summary.open} open leads</strong><span>Review active follow-up across your visible work.</span></div><Link href={crmLeadHref(model.filters,{status:"open"})}>Review leads</Link></li>{early&&<li><div><strong>{early.count} in {early.name}</strong><span>Current leads in the first active pipeline stage.</span></div><Link href="/crm/pipeline">View stage</Link></li>}<li><div><strong>{model.recentActivity.length} recent updates</strong><span>Latest activity from this filtered lead population.</span></div><a href="#recent-activity">Review activity</a></li></ul></section></div>
    <div className="dashboard-two-column"><section className="dashboard-card" aria-labelledby="owners-title"><div className="card-heading"><h3 id="owners-title">Ownership workload</h3></div>{model.owners.length?<ul className="compact-metrics">{model.owners.map(owner=><li key={owner.membershipId}><span>{owner.displayName}</span><b>{owner.count}</b></li>)}</ul>:<p className="helper">No owner workload matches this view.</p>}</section><section className="dashboard-card" aria-labelledby="teams-title"><div className="card-heading"><h3 id="teams-title">Team-visible work</h3></div>{model.teams.length?<ul className="compact-metrics">{model.teams.map(team=><li key={team.teamId}><span>{team.name}</span><b>{team.count}</b></li>)}</ul>:<p className="helper">No team-assigned leads match this view.</p>}</section></div>
    <section className="dashboard-card recent-card" id="recent-activity" aria-labelledby="activity-title"><div className="card-heading"><div><p className="eyebrow">Authorized lead activity</p><h3 id="activity-title">Recent activity</h3></div></div>{model.recentActivity.length?<ol className="dashboard-activity">{model.recentActivity.map(activity=><li key={activity.activityId}><span className="activity-dot" aria-hidden="true"/><div><div><Link href={`/crm/leads/${activity.leadId}`}>{activity.leadLabel}</Link><span>{activity.kind}</span></div><p>{activity.bodyPreview}</p><small>{activity.actorLabel} · <time dateTime={activity.occurredAt}>{new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(activity.occurredAt))}</time></small></div></li>)}</ol>:<p className="helper">No activity is available for this dashboard view.</p>}</section>
  </section>
  <section className="dashboard-section demo-region" aria-labelledby="coming-title"><div className="dashboard-section-heading"><div><span className="demo-badge">Demo preview</span><h2 id="coming-title">Coming next</h2></div><p>{CRM_HOME_DEMO_PREVIEW.notice}</p></div><div className="demo-grid">{CRM_HOME_DEMO_PREVIEW.cards.map(card=><article key={card.title}><span className="demo-badge">Demo preview</span><h3>{card.title}</h3><strong>{card.value}</strong><p>{card.detail}</p><small>{CRM_HOME_DEMO_PREVIEW.notice}</small><span className="coming-label">Coming later</span></article>)}</div></section>
  </>}

export default async function CrmHomePage({searchParams}:{searchParams:Promise<CrmHomeRawFilters>}){const raw=await searchParams,{pool,workspace,context,identity}=await crmPageContext("/crm/home");try{let model:CrmHomeModel;try{model=await crmHome(pool,identity,workspace.id,raw)}catch(error){const safe=error instanceof CrmHomeError?error:new CrmHomeError("dashboard_unavailable",500);if(safe.code==="dashboard_unavailable")console.error("crm_home_read_failed",{correlationId:crypto.randomUUID()});return <CrmShell workspace={workspace.name} role={context.role}><DashboardError code={safe.code}/></CrmShell>}return <CrmShell workspace={model.workspace.name} role={model.actor.role}><section className="admin-content crm-home"><header className="product-page-header crm-home-heading"><div><p className="eyebrow">Workspace overview</p><h1>CRM home</h1><p className="lead">See the customer work you can access in this Workspace.</p></div><div className="product-page-actions"><ActionLink variant="primary" href="/crm/leads/new">Add lead</ActionLink></div></header><LiveDashboard model={model}/></section></CrmShell>}finally{await pool.end()}}
