import Link from "next/link";
import { CrmShell } from "../crm-shell";
import { crmPageContext } from "@/server/crm/page";
import { CrmHomeError, crmHome, type CrmHomeModel, type CrmHomeRawFilters } from "@/server/crm/home";
import { CRM_HOME_DEMO_PREVIEW } from "./demo";
import { crmLeadHref, hasCrmHomeFilters } from "@/server/crm/home-links";
import { ActionLink, Button, ProductPageHeader } from "@/frontend/design-system";
import { Briefcase, ChevronDown, CircleCheck, CircleDot, CircleX, Users } from "lucide-react";
import type { ReactNode } from "react";

export const dynamic="force-dynamic";
export const metadata={title:"CRM home | NexaFlow"};

// Literal Tailwind widths so the bar carries no inline style prop, which
// tests/design-system-boundary.test.ts forbids in production sources. Rounded to the
// nearest 5% - the bar is a proportion cue, and aria-valuenow carries the exact count.
const PROGRESS_WIDTHS=["w-[0%]","w-[5%]","w-[10%]","w-[15%]","w-[20%]","w-[25%]","w-[30%]","w-[35%]","w-[40%]",
  "w-[45%]","w-[50%]","w-[55%]","w-[60%]","w-[65%]","w-[70%]","w-[75%]","w-[80%]","w-[85%]","w-[90%]","w-[95%]","w-[100%]"] as const;
function progressWidth(value:number,maximum:number){
  const ratio=Math.min(100,Math.max(0,(value/Math.max(1,maximum))*100));
  return PROGRESS_WIDTHS[Math.round(ratio/5)];
}

function DashboardError({code}:{code:CrmHomeError["code"]}){const invalid=code==="invalid_filter",missing=code==="resource_not_found";return <section className="mx-auto grid w-full max-w-[1400px] gap-5 py-5" aria-labelledby="crm-home-title"><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">CRM</p><h1 id="crm-home-title">CRM home</h1><div className="my-3 rounded-card border border-accent/30 bg-accent-soft p-3 text-xs text-accent-ink border-danger/30 bg-danger-soft text-danger" role="alert"><div><b>{invalid?"Review the dashboard filters and try again.":missing?"This dashboard view is unavailable.":"We couldn’t load your CRM overview. Try again."}</b><p>No workspace metrics or sample previews are shown while live data is unavailable.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{invalid||missing?<ActionLink variant="primary" className="disabled:opacity-45 no-underline" href="/crm/home">Clear filters</ActionLink>:<ActionLink variant="primary" className="disabled:opacity-45 no-underline" href="/crm/home">Try again</ActionLink>}<ActionLink variant="secondary" className="disabled:opacity-45 no-underline" href="/crm">Go to leads</ActionLink></div></section>}

const filterPill="h-9 min-w-0 appearance-none rounded-full border border-line bg-surface pl-3.5 pr-8 text-xs font-medium text-ink-muted transition-colors hover:border-accent focus:border-accent focus:text-ink focus:outline-none";

function FilterPill({label,name,defaultValue,children}:{label:string;name:string;defaultValue:string;children:ReactNode}){return <span className="relative inline-flex items-center"><label className="sr-only" htmlFor={`crm-home-filter-${name}`}>{label}</label><select id={`crm-home-filter-${name}`} name={name} defaultValue={defaultValue} className={filterPill}>{children}</select><ChevronDown aria-hidden="true" className="pointer-events-none absolute right-3 size-3.5 text-ink-faint"/></span>}

function FilterForm({model}:{model:CrmHomeModel}){const{filters,options,actor}=model;return <form className="flex flex-wrap items-center gap-2" action="/crm/home" aria-label="Filter CRM snapshot"><FilterPill label="Status" name="status" defaultValue={filters.status}><option value="all">All outcomes</option><option value="open">Open</option><option value="won">Won</option><option value="lost">Lost</option></FilterPill><FilterPill label="Stage" name="stage" defaultValue={filters.stage}><option value="all">All stages</option>{options.stages.map(option=><option key={option.id} value={option.id}>{option.label}{option.archived?" — Archived":""}</option>)}</FilterPill><FilterPill label="Owner" name="owner" defaultValue={filters.owner}><option value="all">All owners</option><option value="mine">Mine</option>{options.owners.filter(option=>option.id!==actor.membershipId).map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</FilterPill><FilterPill label="Team" name="team" defaultValue={filters.team}><option value="all">All permitted teams</option>{options.teams.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</FilterPill><FilterPill label="Created" name="period" defaultValue={filters.period}><option value="all">Any time</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></FilterPill><Button variant="primary" className="h-9 min-h-0 rounded-full px-4 py-0 text-xs disabled:opacity-45">Apply</Button>{hasCrmHomeFilters(filters)&&<ActionLink variant="tertiary" className="h-9 min-h-0 rounded-full px-3 py-0 text-xs no-underline" href="/crm/home">Clear</ActionLink>}</form>}

function LiveDashboard({model}:{model:CrmHomeModel}){const max=Math.max(1,...model.pipeline.map(stage=>stage.count)),hasFilters=hasCrmHomeFilters(model.filters),early=model.pipeline.find(stage=>!stage.archived);return <>
  <section className="grid items-center gap-6 rounded-panel border border-accent/30 bg-accent-soft p-6 lg:grid-cols-[1fr_180px]" aria-labelledby="welcome-title"><div><span className="inline-flex rounded-full bg-success-soft px-2.5 py-1 text-[10px] font-bold text-success">Live workspace data</span><p className="mt-3 text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">{model.workspace.name}</p><h2 className="mt-1 text-xl font-semibold text-ink" id="welcome-title">Welcome back. Let’s move customer work forward.</h2><p className="mt-2 text-ink-muted">Your dashboard reflects only the Leads and activity you are authorized to access.</p><div className="mt-4 flex flex-wrap gap-2"><ActionLink variant="primary" href="/crm/leads/new">Add lead</ActionLink><ActionLink href="/crm">View leads</ActionLink></div></div><div className="grid gap-1 rounded-card border border-line bg-surface p-5 text-right" aria-label={`${model.summary.open} open leads`}><div className="flex items-center justify-between gap-2 text-left"><span className="text-xs text-ink-muted">Open leads</span><span aria-hidden="true" className="grid size-[34px] shrink-0 place-items-center rounded-lg bg-accent-soft text-accent-ink [&_svg]:size-[17px]"><Briefcase/></span></div><strong className="text-3xl font-semibold text-ink">{model.summary.open}</strong></div></section>
  <div className="mt-1"><FilterForm model={model}/></div>{model.filters.period!=="all"&&<p className="my-3 text-xs font-semibold text-ink-muted">Leads created in the last {model.filters.period.replace("d","")} days.</p>}
  <p className="sr-only" aria-live="polite">{model.summary.visible} visible leads match this dashboard view.</p>
  <section className="mt-6" aria-labelledby="snapshot-title"><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">Live workspace data</p><h2 id="snapshot-title">CRM snapshot</h2></div><p>Generated <time dateTime={model.generatedAt}>{new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(new Date(model.generatedAt))} UTC</time></p></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Link href={crmLeadHref(model.filters)} className="grid gap-1 rounded-card border border-line bg-surface p-4 hover:border-accent"><div className="flex items-start justify-between gap-2"><span className="text-xs font-semibold text-ink-muted">Visible leads</span><span aria-hidden="true" className="grid size-[34px] shrink-0 place-items-center rounded-lg bg-accent-soft text-accent-ink [&_svg]:size-[17px]"><Users/></span></div><strong className="text-2xl font-semibold text-ink">{model.summary.visible}</strong><small className="text-ink-faint">Authorized current population</small></Link><Link href={crmLeadHref(model.filters,{status:"open"})} className="grid gap-1 rounded-card border border-line bg-surface p-4 hover:border-accent"><div className="flex items-start justify-between gap-2"><span className="text-xs font-semibold text-ink-muted">Open</span><span aria-hidden="true" className="grid size-[34px] shrink-0 place-items-center rounded-lg bg-accent-soft text-accent-ink [&_svg]:size-[17px]"><CircleDot/></span></div><strong className="text-2xl font-semibold text-ink">{model.summary.open}</strong><small className="text-ink-faint">Current lead outcome</small></Link><Link href={crmLeadHref(model.filters,{status:"won"})} className="grid gap-1 rounded-card border border-line bg-surface p-4 hover:border-accent"><div className="flex items-start justify-between gap-2"><span className="text-xs font-semibold text-ink-muted">Won</span><span aria-hidden="true" className="grid size-[34px] shrink-0 place-items-center rounded-lg bg-success-soft text-success [&_svg]:size-[17px]"><CircleCheck/></span></div><strong className="text-2xl font-semibold text-ink">{model.summary.won}</strong><small className="text-ink-faint">Lead outcome, not revenue</small></Link><Link href={crmLeadHref(model.filters,{status:"lost"})} className="grid gap-1 rounded-card border border-line bg-surface p-4 hover:border-accent"><div className="flex items-start justify-between gap-2"><span className="text-xs font-semibold text-ink-muted">Lost</span><span aria-hidden="true" className="grid size-[34px] shrink-0 place-items-center rounded-lg bg-danger-soft text-danger [&_svg]:size-[17px]"><CircleX/></span></div><strong className="text-2xl font-semibold text-ink">{model.summary.lost}</strong><small className="text-ink-faint">Lead outcome, not conversion</small></Link></div>
    {model.summary.visible===0?<div className="grid gap-3 rounded-panel border border-dashed border-line bg-surface p-6 text-ink-muted"><h3>{hasFilters?"No leads match these filters.":"No leads to summarize yet."}</h3><p>{hasFilters?"Clear filters to return to the full authorized snapshot.":"Add a lead to begin tracking customer work."}</p>{hasFilters?<ActionLink variant="secondary" className="disabled:opacity-45 no-underline" href="/crm/home">Clear filters</ActionLink>:<ActionLink variant="primary" className="disabled:opacity-45 no-underline" href="/crm/leads/new">Add lead</ActionLink>}</div>:null}
    <div className="grid gap-4 xl:grid-cols-[1.55fr_1fr]"><section className="rounded-panel border border-line bg-surface p-5" aria-labelledby="pipeline-health"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">Current snapshot</p><h3 id="pipeline-health">Pipeline health</h3></div><Link href="/crm/pipeline">Open pipeline</Link></div><ul className="grid gap-3">{model.pipeline.map(stage=><li key={stage.stageId}><div className="flex items-center justify-between gap-3"><span>{stage.name}{stage.archived?" (Archived)":""}</span><b>{stage.count}</b></div><div role="progressbar" aria-valuenow={stage.count} aria-valuemin={0} aria-valuemax={max} aria-label={`${stage.name}: ${stage.count} Leads`} className="h-1.5 w-full overflow-hidden rounded-full bg-surface-muted border border-line-soft"><div className={`h-full rounded-full bg-accent ${progressWidth(stage.count,max)}`}/></div></li>)}</ul></section>
      <section className="rounded-panel border border-line bg-surface p-5" aria-labelledby="attention-title"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">Live signals</p><h3 id="attention-title">Needs attention</h3></div></div><ul className="grid gap-3"> <li className="grid gap-2 border-b border-line-soft pb-3"><div className="grid gap-1"><strong>{model.summary.open} open leads</strong><span className="text-xs text-ink-muted">Review follow-up across your visible work.</span></div><Link className="text-xs font-semibold text-accent-ink" href={crmLeadHref(model.filters,{status:"open"})}>Review leads</Link></li>{early&&<li className="grid gap-2 border-b border-line-soft pb-3"><div className="grid gap-1"><strong>{early.count} in {early.name}</strong><span className="text-xs text-ink-muted">Current leads in the first Pipeline stage.</span></div><Link className="text-xs font-semibold text-accent-ink" href="/crm/pipeline">View stage</Link></li>}<li className="grid gap-2"><div className="grid gap-1"><strong>{model.recentActivity.length} recent updates</strong><span className="text-xs text-ink-muted">Latest activity from this filtered Lead population.</span></div><a className="text-xs font-semibold text-accent-ink" href="#recent-activity">Review activity</a></li></ul></section></div>
    <div className="grid gap-4 xl:grid-cols-[1.55fr_1fr]"><section className="rounded-panel border border-line bg-surface p-5" aria-labelledby="owners-title"><div className="mb-4 flex items-start justify-between gap-3"><h3 id="owners-title">Ownership workload</h3></div>{model.owners.length?<ul className="grid gap-3">{model.owners.map(owner=><li className="flex items-center justify-between gap-3" key={owner.membershipId}><span>{owner.displayName}</span><b>{owner.count}</b></li>)}</ul>:<p className="text-xs leading-5 text-ink-faint">No owner workload matches this view.</p>}</section><section className="rounded-panel border border-line bg-surface p-5" aria-labelledby="teams-title"><div className="mb-4 flex items-start justify-between gap-3"><h3 id="teams-title">Team-visible work</h3></div>{model.teams.length?<ul className="grid gap-3">{model.teams.map(team=><li className="flex items-center justify-between gap-3" key={team.teamId}><span>{team.name}</span><b>{team.count}</b></li>)}</ul>:<p className="text-xs leading-5 text-ink-faint">No team-assigned leads match this view.</p>}</section></div>
    <section className="rounded-panel border border-line bg-surface p-5" id="recent-activity" aria-labelledby="activity-title"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">Authorized Lead activity</p><h3 id="activity-title">Recent activity</h3></div></div>{model.recentActivity.length?<ol className="grid gap-3">{model.recentActivity.map(activity=><li className="grid grid-cols-[auto_minmax(0,1fr)] gap-3 border-b border-line-soft pb-3 last:border-0" key={activity.activityId}><span className="mt-1.5 size-2.5 rounded-full bg-accent" aria-hidden="true"/><div className="grid gap-1"><div className="flex flex-wrap items-center justify-between gap-2"><Link className="font-semibold text-ink" href={`/crm/leads/${activity.leadId}`}>{activity.leadLabel}</Link><span className="text-xs text-ink-faint">{activity.kind}</span></div><p className="text-ink-muted">{activity.bodyPreview}</p><small className="text-ink-faint">{activity.actorLabel} · <time dateTime={activity.occurredAt}>{new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(activity.occurredAt))}</time></small></div></li>)}</ol>:<p className="text-xs leading-5 text-ink-faint">No activity is available for this dashboard view.</p>}</section>
  </section>
  <section className="mt-6 border-t border-line pt-8" aria-labelledby="coming-title"><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><span className="inline-flex rounded-full bg-warning-soft px-2.5 py-1 text-[10px] font-bold text-warning">Demo preview</span><h2 id="coming-title">Coming next</h2></div><p className="text-xs text-ink-faint">{CRM_HOME_DEMO_PREVIEW.notice}</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{CRM_HOME_DEMO_PREVIEW.cards.map(card=><article className="grid gap-2 rounded-card border border-line bg-surface-muted p-4" key={card.title}><span className="inline-flex w-fit rounded-full bg-warning-soft px-2.5 py-1 text-[10px] font-bold text-warning">Demo preview</span><h3>{card.title}</h3><strong className="text-lg text-ink">{card.value}</strong><p className="text-xs text-ink-muted">{card.detail}</p><small className="text-ink-faint">{CRM_HOME_DEMO_PREVIEW.notice}</small><span className="text-[10px] font-bold uppercase tracking-wide text-warning">Coming later</span></article>)}</div></section>
  </>}

export default async function CrmHomePage({searchParams}:{searchParams:Promise<CrmHomeRawFilters>}){const raw=await searchParams,{pool,workspace,context,identity}=await crmPageContext("/crm/home");try{let model:CrmHomeModel;try{model=await crmHome(pool,identity,workspace.id,raw)}catch(error){const safe=error instanceof CrmHomeError?error:new CrmHomeError("dashboard_unavailable",500);if(safe.code==="dashboard_unavailable")console.error("crm_home_read_failed",{correlationId:crypto.randomUUID()});return <CrmShell workspace={workspace.name} role={context.role}><DashboardError code={safe.code}/></CrmShell>}return <CrmShell workspace={model.workspace.name} role={model.actor.role}><section className="mx-auto grid w-full max-w-[1400px] gap-5 py-5"><ProductPageHeader context="Home" title="Welcome to your workspace" description={<p>Start with a customer or lead, keep the next action clear, and use the overview below when you need the bigger picture.</p>}/><LiveDashboard model={model}/></section></CrmShell>}finally{await pool.end()}}
