import Link from "next/link";
import { CrmShell } from "../crm-shell";
import { crmPageContext } from "@/server/crm/page";
import { CrmHomeError, crmHome, type CrmHomeModel, type CrmHomeRawFilters } from "@/server/crm/home";
import { CRM_HOME_DEMO_PREVIEW } from "./demo";
import { crmLeadHref, hasCrmHomeFilters } from "@/server/crm/home-links";
import { ActionLink, ProductPageHeader } from "@/frontend/design-system";

export const dynamic="force-dynamic";
export const metadata={title:"CRM home | NexaFlow"};

function DashboardError({code}:{code:CrmHomeError["code"]}){const invalid=code==="invalid_filter",missing=code==="resource_not_found";return <section className="mx-auto grid w-full max-w-[1400px] gap-5 py-5" aria-labelledby="crm-home-title"><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">CRM</p><h1 id="crm-home-title">CRM home</h1><div className="my-3 rounded-card border border-accent/30 bg-accent-soft p-3 text-xs text-accent-ink border-danger/30 bg-danger-soft text-danger" role="alert"><div><b>{invalid?"Review the dashboard filters and try again.":missing?"This dashboard view is unavailable.":"We couldn’t load your CRM overview. Try again."}</b><p>No workspace metrics or sample previews are shown while live data is unavailable.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{invalid||missing?<Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control border border-accent bg-accent px-3.5 py-2 text-[12.5px] font-semibold text-on-accent hover:bg-accent-ink disabled:opacity-45 no-underline" href="/crm/home">Clear filters</Link>:<Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control border border-accent bg-accent px-3.5 py-2 text-[12.5px] font-semibold text-on-accent hover:bg-accent-ink disabled:opacity-45 no-underline" href="/crm/home">Try again</Link>}<Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control border border-line bg-surface px-3.5 py-2 text-[12.5px] font-semibold text-ink hover:bg-surface-muted disabled:opacity-45 no-underline" href="/crm">Go to leads</Link></div></section>}

function FilterForm({model}:{model:CrmHomeModel}){const{filters,options,actor}=model;return <form className="grid items-end gap-3 rounded-panel border border-line bg-surface p-4 sm:grid-cols-2 xl:grid-cols-5" action="/crm/home" aria-label="Filter CRM snapshot"><label>Status<select name="status" defaultValue={filters.status}><option value="all">All outcomes</option><option value="open">Open</option><option value="won">Won</option><option value="lost">Lost</option></select></label><label>Stage<select name="stage" defaultValue={filters.stage}><option value="all">All stages</option>{options.stages.map(option=><option key={option.id} value={option.id}>{option.label}{option.archived?" — Archived":""}</option>)}</select></label><label>Owner<select name="owner" defaultValue={filters.owner}><option value="all">All owners</option><option value="mine">Mine</option>{options.owners.filter(option=>option.id!==actor.membershipId).map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><label>Team<select name="team" defaultValue={filters.team}><option value="all">All permitted teams</option>{options.teams.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><label>Created<select name="period" defaultValue={filters.period}><option value="all">Any time</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></label><div className="flex flex-wrap gap-2 sm:col-span-2 xl:col-span-5"><button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control border border-accent bg-accent px-3.5 py-2 text-[12.5px] font-semibold text-on-accent hover:bg-accent-ink disabled:opacity-45">Apply filters</button>{hasCrmHomeFilters(filters)&&<Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control border border-line bg-surface px-3.5 py-2 text-[12.5px] font-semibold text-ink hover:bg-surface-muted disabled:opacity-45 no-underline" href="/crm/home">Clear filters</Link>}</div></form>}

function LiveDashboard({model}:{model:CrmHomeModel}){const max=Math.max(1,...model.pipeline.map(stage=>stage.count)),hasFilters=hasCrmHomeFilters(model.filters),early=model.pipeline.find(stage=>!stage.archived);return <>
  <section className="grid items-center gap-6 rounded-panel border border-line bg-surface p-6 lg:grid-cols-[1fr_180px]" aria-labelledby="welcome-title"><div><span className="live-badge">Live workspace data</span><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">{model.workspace.name}</p><h2 id="welcome-title">Welcome back. Let’s move customer work forward.</h2><p>Your dashboard reflects only the Leads and activity you are authorized to access.</p><div className="mt-4 flex flex-wrap gap-2"><ActionLink variant="primary" href="/crm/leads/new">Add lead</ActionLink><ActionLink href="/crm">View leads</ActionLink></div></div><div className="welcome-stat" aria-label={`${model.summary.open} open leads`}><strong>{model.summary.open}</strong><span>open leads</span></div></section>
  <FilterForm model={model}/>{model.filters.period!=="all"&&<p className="my-3 text-xs font-semibold text-ink-muted">Leads created in the last {model.filters.period.replace("d","")} days.</p>}
  <p className="sr-only" aria-live="polite">{model.summary.visible} visible leads match this dashboard view.</p>
  <section className="mt-6" aria-labelledby="snapshot-title"><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">Live workspace data</p><h2 id="snapshot-title">CRM snapshot</h2></div><p>Generated <time dateTime={model.generatedAt}>{new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(new Date(model.generatedAt))} UTC</time></p></div>
    <div className="kpi-grid"><Link href={crmLeadHref(model.filters)} className="kpi-card"><span>Visible leads</span><strong>{model.summary.visible}</strong><small>Authorized current population</small></Link><Link href={crmLeadHref(model.filters,{status:"open"})} className="kpi-card"><span>Open</span><strong>{model.summary.open}</strong><small>Current lead outcome</small></Link><Link href={crmLeadHref(model.filters,{status:"won"})} className="kpi-card"><span>Won</span><strong>{model.summary.won}</strong><small>Lead outcome, not revenue</small></Link><Link href={crmLeadHref(model.filters,{status:"lost"})} className="kpi-card"><span>Lost</span><strong>{model.summary.lost}</strong><small>Lead outcome, not conversion</small></Link></div>
    {model.summary.visible===0?<div className="empty dashboard-rounded-panel border border-dashed border-line bg-surface p-6 text-ink-muted"><h3>{hasFilters?"No leads match these filters.":"No leads to summarize yet."}</h3><p>{hasFilters?"Clear filters to return to the full authorized snapshot.":"Add a lead to begin tracking customer work."}</p>{hasFilters?<Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control border border-line bg-surface px-3.5 py-2 text-[12.5px] font-semibold text-ink hover:bg-surface-muted disabled:opacity-45 no-underline" href="/crm/home">Clear filters</Link>:<Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control border border-accent bg-accent px-3.5 py-2 text-[12.5px] font-semibold text-on-accent hover:bg-accent-ink disabled:opacity-45 no-underline" href="/crm/leads/new">Add lead</Link>}</div>:null}
    <div className="grid gap-4 xl:grid-cols-[1.55fr_1fr]"><section className="rounded-panel border border-line bg-surface p-5" aria-labelledby="pipeline-health"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">Current snapshot</p><h3 id="pipeline-health">Pipeline health</h3></div><Link href="/crm/pipeline">Open pipeline</Link></div><ul className="grid gap-3">{model.pipeline.map(stage=><li key={stage.stageId}><div className="flex items-center justify-between gap-3"><span>{stage.name}{stage.archived?" (Archived)":""}</span><b>{stage.count}</b></div><progress className="h-2 w-full overflow-hidden rounded-full accent-accent" max={max} value={stage.count} aria-label={`${stage.name}: ${stage.count} Leads`}/></li>)}</ul></section>
      <section className="rounded-panel border border-line bg-surface p-5" aria-labelledby="attention-title"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">Live signals</p><h3 id="attention-title">Needs attention</h3></div></div><ul className="grid gap-3"><li><div><strong>{model.summary.open} open leads</strong><span>Review bg-accent-soft text-accent-ink follow-up across your visible work.</span></div><Link href={crmLeadHref(model.filters,{status:"open"})}>Review leads</Link></li>{early&&<li><div><strong>{early.count} in {early.name}</strong><span>Current leads in the first bg-accent-soft text-accent-ink pipeline stage.</span></div><Link href="/crm/pipeline">View stage</Link></li>}<li><div><strong>{model.recentActivity.length} recent updates</strong><span>Latest activity from this filtered lead population.</span></div><a href="#recent-activity">Review activity</a></li></ul></section></div>
    <div className="grid gap-4 xl:grid-cols-[1.55fr_1fr]"><section className="rounded-panel border border-line bg-surface p-5" aria-labelledby="owners-title"><div className="mb-4 flex items-start justify-between gap-3"><h3 id="owners-title">Ownership workload</h3></div>{model.owners.length?<ul className="grid gap-3">{model.owners.map(owner=><li key={owner.membershipId}><span>{owner.displayName}</span><b>{owner.count}</b></li>)}</ul>:<p className="text-xs leading-5 text-ink-faint">No owner workload matches this view.</p>}</section><section className="rounded-panel border border-line bg-surface p-5" aria-labelledby="teams-title"><div className="mb-4 flex items-start justify-between gap-3"><h3 id="teams-title">Team-visible work</h3></div>{model.teams.length?<ul className="grid gap-3">{model.teams.map(team=><li key={team.teamId}><span>{team.name}</span><b>{team.count}</b></li>)}</ul>:<p className="text-xs leading-5 text-ink-faint">No team-assigned leads match this view.</p>}</section></div>
    <section className="rounded-panel border border-line bg-surface p-5 recent-card" id="recent-activity" aria-labelledby="activity-title"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[10.5px] font-bold uppercase tracking-[.08em] text-ink-faint">Authorized lead activity</p><h3 id="activity-title">Recent activity</h3></div></div>{model.recentActivity.length?<ol className="grid gap-3">{model.recentActivity.map(activity=><li key={activity.activityId}><span className="size-2.5 rounded-full bg-accent" aria-hidden="true"/><div><div><Link href={`/crm/leads/${activity.leadId}`}>{activity.leadLabel}</Link><span>{activity.kind}</span></div><p>{activity.bodyPreview}</p><small>{activity.actorLabel} · <time dateTime={activity.occurredAt}>{new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(activity.occurredAt))}</time></small></div></li>)}</ol>:<p className="text-xs leading-5 text-ink-faint">No activity is available for this dashboard view.</p>}</section>
  </section>
  <section className="mt-6 border-t border-line pt-8" aria-labelledby="coming-title"><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><span className="inline-flex rounded-full bg-warning-soft px-2.5 py-1 text-[10px] font-bold text-warning">Demo preview</span><h2 id="coming-title">Coming next</h2></div><p>{CRM_HOME_DEMO_PREVIEW.notice}</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{CRM_HOME_DEMO_PREVIEW.cards.map(card=><article key={card.title}><span className="inline-flex rounded-full bg-warning-soft px-2.5 py-1 text-[10px] font-bold text-warning">Demo preview</span><h3>{card.title}</h3><strong>{card.value}</strong><p>{card.detail}</p><small>{CRM_HOME_DEMO_PREVIEW.notice}</small><span className="coming-label">Coming later</span></article>)}</div></section>
  </>}

export default async function CrmHomePage({searchParams}:{searchParams:Promise<CrmHomeRawFilters>}){const raw=await searchParams,{pool,workspace,context,identity}=await crmPageContext("/crm/home");try{let model:CrmHomeModel;try{model=await crmHome(pool,identity,workspace.id,raw)}catch(error){const safe=error instanceof CrmHomeError?error:new CrmHomeError("dashboard_unavailable",500);if(safe.code==="dashboard_unavailable")console.error("crm_home_read_failed",{correlationId:crypto.randomUUID()});return <CrmShell workspace={workspace.name} role={context.role}><DashboardError code={safe.code}/></CrmShell>}return <CrmShell workspace={model.workspace.name} role={model.actor.role}><section className="mx-auto grid w-full max-w-[1400px] gap-5 py-5"><ProductPageHeader context="Home" title="Welcome to your workspace" description={<p>Start with a customer or lead, keep the next action clear, and use the overview below when you need the bigger picture.</p>}/><LiveDashboard model={model}/></section></CrmShell>}finally{await pool.end()}}
