ALTER TABLE "companies" ADD COLUMN "website_url" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "industry" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "size_band" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "employee_count" integer;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "annual_revenue_minor" numeric(20, 0);--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "annual_revenue_currency_code" char(3);--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "annual_revenue_currency_exponent" integer;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "parent_company_id" uuid;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "phone_display" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "street" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "city" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "state_province" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "postal_code" text;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "country" text;--> statement-breakpoint
ALTER TABLE "contact_identity_points" ADD COLUMN "channel_usage" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "salutation" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "job_title" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "department" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "linkedin_url" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "lifecycle_stage" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "street" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "city" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "state_province" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "postal_code" text;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "country" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "salutation" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "job_title" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "secondary_email_normalized" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "secondary_email_display" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "mobile_phone_display" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "mobile_phone_normalized" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "mobile_phone_country_code_used" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "fax_display" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "fax_normalized" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "fax_country_code_used" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "website_url" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "twitter_handle" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "promotional_email_opt_out" boolean;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "promotional_email_opt_out_recorded_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "promotional_email_opt_out_source" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "rating" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "industry" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "annual_revenue_minor" numeric(20, 0);--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "annual_revenue_currency_code" char(3);--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "annual_revenue_currency_exponent" integer;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "employee_count" integer;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "street" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "city" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "state_province" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "postal_code" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "country" text;--> statement-breakpoint
ALTER TABLE "companies" ADD CONSTRAINT "companies_parent_company_fk" FOREIGN KEY ("workspace_id","parent_company_id") REFERENCES "public"."companies"("workspace_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "companies_parent_lookup_idx" ON "companies" USING btree ("workspace_id","parent_company_id","id") WHERE "companies"."parent_company_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "contact_identity_points_active_usage_uq" ON "contact_identity_points" USING btree ("workspace_id","contact_id","channel_usage") WHERE "contact_identity_points"."lifecycle"='active' and "contact_identity_points"."channel_usage" is not null;--> statement-breakpoint
ALTER TABLE "companies" ADD CONSTRAINT "companies_profile_fields_check" CHECK (("companies"."website_url" is null or (char_length("companies"."website_url") between 1 and 500 and "companies"."website_url"=btrim("companies"."website_url") and "companies"."website_url" !~ '[[:cntrl:]]')) and ("companies"."industry" is null or (char_length("companies"."industry") between 1 and 120 and "companies"."industry"=btrim("companies"."industry") and "companies"."industry" !~ '[[:cntrl:]]')) and ("companies"."phone_display" is null or (char_length("companies"."phone_display") between 1 and 50 and "companies"."phone_display"=btrim("companies"."phone_display") and "companies"."phone_display" !~ '[[:cntrl:]]')));--> statement-breakpoint
ALTER TABLE "companies" ADD CONSTRAINT "companies_size_band_check" CHECK ("companies"."size_band" is null or "companies"."size_band" in ('micro','small','medium','large','enterprise'));--> statement-breakpoint
ALTER TABLE "companies" ADD CONSTRAINT "companies_employee_count_check" CHECK ("companies"."employee_count" is null or "companies"."employee_count" between 0 and 2147483647);--> statement-breakpoint
ALTER TABLE "companies" ADD CONSTRAINT "companies_annual_revenue_check" CHECK ((num_nonnulls("companies"."annual_revenue_minor","companies"."annual_revenue_currency_code","companies"."annual_revenue_currency_exponent")=0) or (num_nonnulls("companies"."annual_revenue_minor","companies"."annual_revenue_currency_code","companies"."annual_revenue_currency_exponent")=3 and "companies"."annual_revenue_minor" between 0 and 99999999999999999999 and "companies"."annual_revenue_currency_code" in ('USD','CAD') and "companies"."annual_revenue_currency_exponent"=2));--> statement-breakpoint
ALTER TABLE "companies" ADD CONSTRAINT "companies_parent_self_check" CHECK ("companies"."parent_company_id" is null or "companies"."parent_company_id"<>"companies"."id");--> statement-breakpoint
ALTER TABLE "companies" ADD CONSTRAINT "companies_postal_address_check" CHECK (("companies"."street" is null or (char_length("companies"."street") between 1 and 255 and "companies"."street"=btrim("companies"."street") and "companies"."street" !~ '[[:cntrl:]]')) and ("companies"."city" is null or (char_length("companies"."city") between 1 and 100 and "companies"."city"=btrim("companies"."city") and "companies"."city" !~ '[[:cntrl:]]')) and ("companies"."state_province" is null or (char_length("companies"."state_province") between 1 and 100 and "companies"."state_province"=btrim("companies"."state_province") and "companies"."state_province" !~ '[[:cntrl:]]')) and ("companies"."postal_code" is null or (char_length("companies"."postal_code") between 1 and 30 and "companies"."postal_code"=btrim("companies"."postal_code") and "companies"."postal_code" !~ '[[:cntrl:]]')) and ("companies"."country" is null or (char_length("companies"."country") between 1 and 100 and "companies"."country"=btrim("companies"."country") and "companies"."country" !~ '[[:cntrl:]]')));--> statement-breakpoint
ALTER TABLE "contact_identity_points" ADD CONSTRAINT "contact_identity_points_usage_check" CHECK ("contact_identity_points"."channel_usage" is null or (("contact_identity_points"."kind"='email' and "contact_identity_points"."channel_usage" in ('email_primary','email_secondary')) or ("contact_identity_points"."kind"='phone' and "contact_identity_points"."channel_usage" in ('phone_primary','phone_direct','phone_mobile'))) and ("contact_identity_points"."channel_usage" in ('email_primary','phone_primary'))="contact_identity_points"."is_primary");--> statement-breakpoint
ALTER TABLE "contacts" ADD CONSTRAINT "contacts_profile_fields_check" CHECK (("contacts"."salutation" is null or (char_length("contacts"."salutation") between 1 and 20 and "contacts"."salutation"=btrim("contacts"."salutation") and "contacts"."salutation" !~ '[[:cntrl:]]')) and ("contacts"."job_title" is null or (char_length("contacts"."job_title") between 1 and 160 and "contacts"."job_title"=btrim("contacts"."job_title") and "contacts"."job_title" !~ '[[:cntrl:]]')) and ("contacts"."department" is null or (char_length("contacts"."department") between 1 and 120 and "contacts"."department"=btrim("contacts"."department") and "contacts"."department" !~ '[[:cntrl:]]')) and ("contacts"."linkedin_url" is null or (char_length("contacts"."linkedin_url") between 1 and 500 and "contacts"."linkedin_url"=btrim("contacts"."linkedin_url") and "contacts"."linkedin_url" !~ '[[:cntrl:]]')));--> statement-breakpoint
ALTER TABLE "contacts" ADD CONSTRAINT "contacts_lifecycle_stage_check" CHECK ("contacts"."lifecycle_stage" is null or "contacts"."lifecycle_stage" in ('lead','marketing_qualified','sales_qualified','opportunity','customer','evangelist','other'));--> statement-breakpoint
ALTER TABLE "contacts" ADD CONSTRAINT "contacts_postal_address_check" CHECK (("contacts"."street" is null or (char_length("contacts"."street") between 1 and 255 and "contacts"."street"=btrim("contacts"."street") and "contacts"."street" !~ '[[:cntrl:]]')) and ("contacts"."city" is null or (char_length("contacts"."city") between 1 and 100 and "contacts"."city"=btrim("contacts"."city") and "contacts"."city" !~ '[[:cntrl:]]')) and ("contacts"."state_province" is null or (char_length("contacts"."state_province") between 1 and 100 and "contacts"."state_province"=btrim("contacts"."state_province") and "contacts"."state_province" !~ '[[:cntrl:]]')) and ("contacts"."postal_code" is null or (char_length("contacts"."postal_code") between 1 and 30 and "contacts"."postal_code"=btrim("contacts"."postal_code") and "contacts"."postal_code" !~ '[[:cntrl:]]')) and ("contacts"."country" is null or (char_length("contacts"."country") between 1 and 100 and "contacts"."country"=btrim("contacts"."country") and "contacts"."country" !~ '[[:cntrl:]]')));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_secondary_email_pair_check" CHECK (("leads"."secondary_email_display" is null)=("leads"."secondary_email_normalized" is null));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_secondary_email_check" CHECK ("leads"."secondary_email_normalized" is null or (char_length("leads"."secondary_email_display") between 3 and 320 and "leads"."secondary_email_display"=btrim("leads"."secondary_email_display") and "leads"."secondary_email_display" !~ '[[:cntrl:]]' and char_length("leads"."secondary_email_normalized") between 3 and 320 and "leads"."secondary_email_normalized"=lower(btrim("leads"."secondary_email_normalized")) and "leads"."secondary_email_normalized" !~ '[[:cntrl:]]'));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_mobile_phone_check" CHECK (("leads"."mobile_phone_display" is null and "leads"."mobile_phone_normalized" is null and "leads"."mobile_phone_country_code_used" is null) or ("leads"."mobile_phone_display" is not null and char_length("leads"."mobile_phone_display") between 1 and 50 and "leads"."mobile_phone_display"=btrim("leads"."mobile_phone_display") and "leads"."mobile_phone_display" !~ '[[:cntrl:]]' and "leads"."mobile_phone_normalized" is not null and char_length("leads"."mobile_phone_normalized") between 3 and 32 and "leads"."mobile_phone_normalized"=btrim("leads"."mobile_phone_normalized") and "leads"."mobile_phone_normalized" !~ '[[:cntrl:]]' and char_length(btrim("leads"."mobile_phone_country_code_used")) between 2 and 16 and "leads"."mobile_phone_country_code_used" !~ '[[:cntrl:]]'));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_fax_check" CHECK (("leads"."fax_display" is null and "leads"."fax_normalized" is null and "leads"."fax_country_code_used" is null) or ("leads"."fax_display" is not null and char_length("leads"."fax_display") between 1 and 50 and "leads"."fax_display"=btrim("leads"."fax_display") and "leads"."fax_display" !~ '[[:cntrl:]]' and "leads"."fax_normalized" is not null and char_length("leads"."fax_normalized") between 3 and 32 and "leads"."fax_normalized"=btrim("leads"."fax_normalized") and "leads"."fax_normalized" !~ '[[:cntrl:]]' and char_length(btrim("leads"."fax_country_code_used")) between 2 and 16 and "leads"."fax_country_code_used" !~ '[[:cntrl:]]'));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_profile_fields_check" CHECK (("leads"."salutation" is null or (char_length("leads"."salutation") between 1 and 20 and "leads"."salutation"=btrim("leads"."salutation") and "leads"."salutation" !~ '[[:cntrl:]]')) and ("leads"."job_title" is null or (char_length("leads"."job_title") between 1 and 160 and "leads"."job_title"=btrim("leads"."job_title") and "leads"."job_title" !~ '[[:cntrl:]]')) and ("leads"."website_url" is null or (char_length("leads"."website_url") between 1 and 500 and "leads"."website_url"=btrim("leads"."website_url") and "leads"."website_url" !~ '[[:cntrl:]]')) and ("leads"."twitter_handle" is null or (char_length("leads"."twitter_handle") between 1 and 50 and "leads"."twitter_handle"=btrim("leads"."twitter_handle") and "leads"."twitter_handle" !~ '[[:cntrl:]]')) and ("leads"."industry" is null or (char_length("leads"."industry") between 1 and 120 and "leads"."industry"=btrim("leads"."industry") and "leads"."industry" !~ '[[:cntrl:]]')));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_consent_fact_check" CHECK (num_nonnulls("leads"."promotional_email_opt_out","leads"."promotional_email_opt_out_recorded_at","leads"."promotional_email_opt_out_source")=0 or (num_nonnulls("leads"."promotional_email_opt_out","leads"."promotional_email_opt_out_recorded_at","leads"."promotional_email_opt_out_source")=3 and "leads"."promotional_email_opt_out_source" in ('manual','import','integration')));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_rating_check" CHECK ("leads"."rating" is null or "leads"."rating" in ('hot','warm','cold'));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_annual_revenue_check" CHECK (num_nonnulls("leads"."annual_revenue_minor","leads"."annual_revenue_currency_code","leads"."annual_revenue_currency_exponent")=0 or (num_nonnulls("leads"."annual_revenue_minor","leads"."annual_revenue_currency_code","leads"."annual_revenue_currency_exponent")=3 and "leads"."annual_revenue_minor" between 0 and 99999999999999999999 and "leads"."annual_revenue_currency_code" in ('USD','CAD') and "leads"."annual_revenue_currency_exponent"=2));--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_employee_count_check" CHECK ("leads"."employee_count" is null or "leads"."employee_count" between 0 and 2147483647);--> statement-breakpoint
ALTER TABLE "leads" ADD CONSTRAINT "leads_postal_address_check" CHECK (("leads"."street" is null or (char_length("leads"."street") between 1 and 255 and "leads"."street"=btrim("leads"."street") and "leads"."street" !~ '[[:cntrl:]]')) and ("leads"."city" is null or (char_length("leads"."city") between 1 and 100 and "leads"."city"=btrim("leads"."city") and "leads"."city" !~ '[[:cntrl:]]')) and ("leads"."state_province" is null or (char_length("leads"."state_province") between 1 and 100 and "leads"."state_province"=btrim("leads"."state_province") and "leads"."state_province" !~ '[[:cntrl:]]')) and ("leads"."postal_code" is null or (char_length("leads"."postal_code") between 1 and 30 and "leads"."postal_code"=btrim("leads"."postal_code") and "leads"."postal_code" !~ '[[:cntrl:]]')) and ("leads"."country" is null or (char_length("leads"."country") between 1 and 100 and "leads"."country"=btrim("leads"."country") and "leads"."country" !~ '[[:cntrl:]]')));
