"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Alert, Shell } from "../onboarding/components";
import { plans, selection, validEmail } from "../onboarding/logic";
type Role = "Member" | "Admin";
type Invite = { email: string; role: Role; status: "pending" | "sent" | "failed" };
export default function InvitePage() { const { plan } = selection(useSearchParams()); const seatLimit = plans[plan].seats - 1; const [input, setInput] = useState(""), [defaultRole, setDefaultRole] = useState<Role>("Member"), [invites, setInvites] = useState<Invite[]>([]), [error, setError] = useState(""), [state, setState] = useState<"idle" | "sent" | "partial" | "failed">("idle");
  function addEmails(value: string) { const entries = value.split(/[\s,;]+/).map((email) => email.trim().toLowerCase()).filter(Boolean); const invalid = entries.find((email) => !validEmail(email)); const duplicate = entries.find((email) => invites.some((invite) => invite.email === email)); if (invalid) return setError("Enter a valid work email address."); if (duplicate) return setError("This person is already a member or has a pending invitation."); if (invites.length + entries.length > seatLimit) return setError(`Your ${plans[plan].name} plan has ${Math.max(0, seatLimit - invites.length)} invitation seat${seatLimit - invites.length === 1 ? "" : "s"} remaining.`); if (entries.length) { setInvites((current) => [...current, ...entries.map((email) => ({ email, role: defaultRole, status: "pending" as const }))]); setError(""); setInput(""); } }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (input.trim()) { addEmails(input); return; } if (!invites.length) return setError("Add at least one work email to send an invitation."); setState("sent"); setInvites((current) => current.map((invite) => ({ ...invite, status: "sent" }))); sessionStorage.setItem("nexaDemoInvites", "sent"); }
  function previewPartial() { if (!invites.length) return setError("Add at least one work email to preview partial success."); setState("partial"); setInvites((current) => current.map((invite, index) => ({ ...invite, status: index === 0 ? "sent" : "failed" }))); }
  function retry(email: string) { setInvites((current) => current.map((invite) => invite.email === email ? { ...invite, status: "sent" } : invite)); setState("sent"); sessionStorage.setItem("nexaDemoInvites", "sent"); }
  return <Shell authLink={false}><p className="eyebrow">Workspace setup</p><h1>Invite your team</h1><p className="lead">Invitations expire after 7 days. Pending invitations don’t use a seat.</p><p className="helper">{plans[plan].name} includes {plans[plan].seats} seat{plans[plan].seats === 1 ? "" : "s"}; {Math.max(0, seatLimit - invites.length)} invitation seat{seatLimit - invites.length === 1 ? "" : "s"} remaining.</p>{(state === "sent" || state === "partial") && <Alert kind="success"><b>{state === "partial" ? "Some invitations were sent." : "Invitations sent."}</b> This local preview did not send email.</Alert>}{state === "failed" && <Alert kind="error">We couldn’t send invitations. Your entries are still here. Try again.</Alert>}{error && <Alert kind="error">{error}</Alert>}<form onSubmit={submit} noValidate><label className="field" htmlFor="invite-email"><span>Work email<em> Required</em></span><div className="input-wrap"><input id="invite-email" value={input} onChange={(event) => setInput(event.target.value)} placeholder="alex@example.com" type="email" autoComplete="email" aria-describedby="invite-help invite-error" /></div><small id="invite-help">Add multiple addresses separated by commas, spaces, or semicolons.</small></label><button type="button" className="secondary add-button" onClick={() => addEmails(input)}>Add</button><label className="field" htmlFor="invite-role"><span>Default role<em> Required</em></span><select id="invite-role" value={defaultRole} onChange={(event) => setDefaultRole(event.target.value as Role)}><option>Member</option><option>Admin</option></select></label><div className="owner-panel"><b>{invites.length ? `${invites.length} invitation${invites.length === 1 ? "" : "s"} ready` : "No invitations added yet"}</b>{invites.map((invite) => <div className="invite-row" key={invite.email}><span>{invite.email}<small>{invite.status === "failed" ? "Couldn’t send" : invite.status === "sent" ? "Sent" : invite.role}</small></span>{invite.status === "failed" ? <button type="button" className="text-button" onClick={() => retry(invite.email)}>Retry</button> : <button type="button" className="chip-remove" aria-label={`Remove ${invite.email}`} onClick={() => setInvites((current) => current.filter((item) => item.email !== invite.email))}>×</button>}</div>)}</div><button className="primary" disabled={state === "sent"}>{state === "sent" ? "Invitations sent" : "Send invitations"}</button></form><div className="preview-actions"><button type="button" className="text-button" onClick={previewPartial}>Preview partial success</button><button type="button" className="text-button" onClick={() => setState("failed")}>Preview network failure</button></div><Link className="secondary link-button" href="/crm" onClick={() => sessionStorage.setItem("nexaDemoInvites", "skipped")}>Skip for now</Link><p className="below"><Link href="/workspace/ready">Back to workspace ready</Link></p></Shell>; }
