/* Literal class names let Tailwind discover every device-local variant. */
export const nexaCrm = {
  shell: "min-[901px]:[[data-interface-style=nexa-crm]_&]:grid-rows-[56px_minmax(0,1fr)] min-[901px]:[[data-interface-style=nexa-crm]_&]:bg-[var(--nx-canvas)]",
  rail: "min-[901px]:[[data-interface-style=nexa-crm]_&]:p-[14px_12px] min-[901px]:[[data-interface-style=nexa-crm]_&]:border-r-[var(--nx-border-strong)]",
  topbar: "min-[901px]:[[data-interface-style=nexa-crm]_&]:min-h-14 min-[901px]:[[data-interface-style=nexa-crm]_&]:px-5",
  main: "min-[901px]:[[data-interface-style=nexa-crm]_&]:px-6 min-[901px]:[[data-interface-style=nexa-crm]_&]:pb-10",
  navGroup: "min-[901px]:[[data-interface-style=nexa-crm]_&]:gap-px",
  navHeading: "min-[901px]:[[data-interface-style=nexa-crm]_&]:min-h-8 min-[901px]:[[data-interface-style=nexa-crm]_&]:px-2 min-[901px]:[[data-interface-style=nexa-crm]_&]:py-1 min-[901px]:[[data-interface-style=nexa-crm]_&]:text-[10px]",
  navList: "min-[901px]:[[data-interface-style=nexa-crm]_&]:gap-px min-[901px]:[[data-interface-style=nexa-crm]_&]:border-l-0 min-[901px]:[[data-interface-style=nexa-crm]_&]:pl-0",
  navItem: "min-[901px]:[[data-interface-style=nexa-crm]_&]:min-h-11 min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-[7px] min-[901px]:[[data-interface-style=nexa-crm]_&]:px-[9px] min-[901px]:[[data-interface-style=nexa-crm]_&]:py-1.5 min-[901px]:[[data-interface-style=nexa-crm]_&]:text-xs",
  search: "min-[901px]:[[data-interface-style=nexa-crm]_&]:min-w-60 min-[901px]:[[data-interface-style=nexa-crm]_&]:bg-[#fbfaf8]",
  pageHeader: "min-[901px]:[[data-interface-style=nexa-crm]_&]:mt-0 min-[901px]:[[data-interface-style=nexa-crm]_&]:items-start min-[901px]:[[data-interface-style=nexa-crm]_&]:py-5 min-[901px]:[[data-interface-style=nexa-crm]_&]:pb-4 min-[901px]:[[data-interface-style=nexa-crm]_&]:[&_h1]:text-2xl",
  action: "min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-lg",
  panel: "min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-[10px] min-[901px]:[[data-interface-style=nexa-crm]_&]:bg-white min-[901px]:[[data-interface-style=nexa-crm]_&]:shadow-[var(--nf-shadow-1)]",
  feedback: "min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-[10px] min-[901px]:[[data-interface-style=nexa-crm]_&]:shadow-[var(--nf-shadow-1)]",
  toolbar: "min-[901px]:[[data-interface-style=nexa-crm]_&]:grid-cols-[minmax(260px,1fr)_auto] min-[901px]:[[data-interface-style=nexa-crm]_&]:gap-3 min-[901px]:[[data-interface-style=nexa-crm]_&]:p-3",
  tableWrap: "min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-[10px] min-[901px]:[[data-interface-style=nexa-crm]_&]:shadow-[var(--nf-shadow-1)] min-[901px]:[[data-interface-style=nexa-crm]_&]:[&_th]:bg-[#fbfaf8] min-[901px]:[[data-interface-style=nexa-crm]_&]:[&_th]:text-[10px] min-[901px]:[[data-interface-style=nexa-crm]_&]:[&_th]:uppercase min-[901px]:[[data-interface-style=nexa-crm]_&]:[&_td]:py-2.5",
  recordCard: "min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-lg min-[901px]:[[data-interface-style=nexa-crm]_&]:bg-white min-[901px]:[[data-interface-style=nexa-crm]_&]:p-3",
  recordWorkspace: "min-[901px]:[[data-interface-style=nexa-crm]_&]:grid-cols-[280px_minmax(0,1fr)] min-[901px]:[[data-interface-style=nexa-crm]_&]:gap-[14px]",
  viewTabs: "min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-lg min-[901px]:[[data-interface-style=nexa-crm]_&]:border min-[901px]:[[data-interface-style=nexa-crm]_&]:bg-white",
  stage: "min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-[10px] min-[901px]:[[data-interface-style=nexa-crm]_&]:bg-[#f1f0ed] min-[901px]:[[data-interface-style=nexa-crm]_&]:p-[9px]",
  formWorkbench: "min-[901px]:[[data-interface-style=nexa-crm]_&]:grid-cols-[184px_minmax(0,1fr)] min-[901px]:[[data-interface-style=nexa-crm]_&]:gap-[14px]",
  formSection: "min-[901px]:[[data-interface-style=nexa-crm]_&]:gap-[14px] min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-[10px] min-[901px]:[[data-interface-style=nexa-crm]_&]:border-l-4 min-[901px]:[[data-interface-style=nexa-crm]_&]:border-l-[var(--ds-section-accent)] min-[901px]:[[data-interface-style=nexa-crm]_&]:bg-white min-[901px]:[[data-interface-style=nexa-crm]_&]:p-[17px_18px]",
  formActions: "min-[901px]:[[data-interface-style=nexa-crm]_&]:gap-2 min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-[10px] min-[901px]:[[data-interface-style=nexa-crm]_&]:bg-[#fbfaf8] min-[901px]:[[data-interface-style=nexa-crm]_&]:p-[10px_13px]",
  sectionNav: "min-[901px]:[[data-interface-style=nexa-crm]_&]:top-3 min-[901px]:[[data-interface-style=nexa-crm]_&]:rounded-[10px] min-[901px]:[[data-interface-style=nexa-crm]_&]:p-2",
} as const;
