"use client";
import Link from "next/link";
import {FormEvent,useRef,useState} from "react";
import type{ErrorEnvelope,IntakeResult,LeadInquiryIntakeCommandV1,SourceCategory,SocialPlatform,SourceMedium}from"../contracts/lead-intake.contracts";
import{sourceCategories,socialPlatforms}from"../contracts/lead-intake.contracts";
type Errors=Record<string,string>;
async function csrf(){const response=await fetch("/api/auth/csrf",{cache:"no-store"});return(response.ok?await response.json():{})as{token?:string}}
function idempotencyKey(){return crypto.randomUUID()}
export function ManualLeadIntakeForm({workspaceId,receivedAt}:{workspaceId:string;receivedAt:string}){
 const summary=useRef<HTMLDivElement>(null),[source,setSource]=useState<SourceCategory>("manual"),[platform,setPlatform]=useState<SocialPlatform|"">(""),[medium,setMedium]=useState<SourceMedium>("unknown"),[busy,setBusy]=useState(false),[errors,setErrors]=useState<Errors>({}),[notice,setNotice]=useState(""),[result,setResult]=useState<IntakeResult|null>(null),key=useRef(idempotencyKey()),bodyHash=useRef("");
 function validate(data:FormData){const next:Errors={},name=String(data.get("displayName")??"").trim(),email=String(data.get("email")??"").trim(),phone=String(data.get("phone")??"").trim();if(!name)next.displayName="Enter a name.";if(!email&&!phone)next.email="Enter an email address or phone number.";if(email&&!/^\S+@\S+\.\S+$/.test(email))next.email="Enter a valid email address.";if(source==="social_media"&&!platform)next.sourcePlatform="Choose a social platform.";if(source!=="social_media"&&platform)next.sourcePlatform="Remove the social platform for this source.";if(platform==="other_social"&&!String(data.get("platformDetail")??"").trim())next.platformDetail="Describe the social platform.";setErrors(next);if(Object.keys(next).length)setTimeout(()=>summary.current?.focus());return!Object.keys(next).length}
 function command(data:FormData):LeadInquiryIntakeCommandV1{const value=(name:string)=>String(data.get(name)??"").trim(),detail:Record<string,string>={};for(const field of["page","account","campaign","ad","form","post"]){const item=value(field);if(item)detail[field]=item}if(platform==="other_social")detail.operator_context=value("platformDetail");const organization=value("organizationName");return{contractVersion:"lead-inquiry-intake.v1",intakeChannel:"manual",person:{displayName:value("displayName"),...(value("email")?{email:value("email")}:{ }),...(value("phone")?{phone:value("phone"),phoneCountryOverride:(value("phoneCountry")||"CA")as"CA"|"US"}:{})},...(organization?{organization:{name:organization,...(value("organizationDomain")?{domain:value("organizationDomain")}:{})}}:{}),inquiry:{...(value("subject")?{subject:value("subject")}:{ }),...(value("message")?{message:value("message")}:{ }),receivedAt},source:{sourceCategory:source,...(source==="social_media"&&platform?{sourcePlatform:platform}:{}),sourceMedium:medium,sourceDetail:detail,campaignContext:{},attributionContractVersion:"p1a-attribution-v1"}}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);if(!validate(data))return;const payload=command(data),serialized=JSON.stringify(payload);if(bodyHash.current&&bodyHash.current!==serialized)key.current=idempotencyKey();bodyHash.current=serialized;setBusy(true);setNotice("Creating lead…");setResult(null);try{const token=await csrf(),response=await fetch(`/api/workspaces/${workspaceId}/leads`,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":token.token??"","idempotency-key":key.current},body:serialized}),envelope=await response.json()as{data?:IntakeResult}&Partial<ErrorEnvelope>;if(response.ok&&envelope.data){setResult(envelope.data);setNotice(envelope.data.replayed?"This lead was already created.":envelope.data.disposition==="held_for_review"?"Lead created and ready for identity review.":"Lead created.");return}const error=envelope.error;setNotice(error?.message??"The lead could not be created.");if(error?.details?.fields?.length)setErrors(Object.fromEntries(error.details.fields.map(field=>[field,"Check this value."])));if(error?.reconciliation.action!=="retry_same_request")key.current=idempotencyKey();setTimeout(()=>summary.current?.focus())}catch{setNotice("Lead intake is temporarily unavailable. Your entries are still here; retry safely.")}finally{setBusy(false)}}
 if(result)return <section className="p1a-result" aria-live="polite"><div className="alert success" role="status"><h2>{notice}</h2><p>The Workspace owns this lead. Original source attribution has been preserved.</p></div><div className="row-actions"><Link className="primary link-button" href={result.nextView.kind==="identity_review_detail"?`/crm/identity-reviews/${result.nextView.leadId}`:`/crm/leads/${result.nextView.leadId}`}>{result.nextView.kind==="identity_review_detail"?"Review possible matches":"View lead"}</Link><button className="secondary" type="button" onClick={()=>{setResult(null);setNotice("");key.current=idempotencyKey();bodyHash.current=""}}>Add another lead</button></div></section>;
 const described=(id:string)=>errors[id]?`${id}-help ${id}-error`:`${id}-help`;
 return <form className="p1a-form" onSubmit={submit} noValidate aria-busy={busy}>{notice&&<div ref={summary} className={`alert ${errors&&Object.keys(errors).length?"error":"info"}`} role={Object.keys(errors).length?"alert":"status"} tabIndex={-1}>{notice}</div>}{Object.keys(errors).length>0&&<div ref={summary} className="alert error error-summary" role="alert" tabIndex={-1}><b>Please correct the following:</b><ul>{Object.entries(errors).map(([field,message])=><li key={field}><a href={`#${field}`}>{message}</a></li>)}</ul></div>}
 <section aria-labelledby="person-heading"><h2 id="person-heading">Person</h2><label className="field"><span>Name</span><input id="displayName" name="displayName" autoComplete="name" aria-invalid={!!errors.displayName} aria-describedby={described("displayName")}/><small id="displayName-help">The name supplied with the inquiry.</small>{errors.displayName&&<small id="displayName-error" className="field-error">{errors.displayName}</small>}</label><div className="form-grid"><label className="field"><span>Email</span><input id="email" name="email" type="email" autoComplete="email" aria-invalid={!!errors.email} aria-describedby={described("email")}/><small id="email-help">Enter at least an email address or phone number.</small>{errors.email&&<small id="email-error" className="field-error">{errors.email}</small>}</label><label className="field"><span>Phone</span><input id="phone" name="phone" type="tel" autoComplete="tel" aria-describedby="phone-help"/><small id="phone-help">Original presentation is preserved.</small></label></div><label className="field"><span>Phone country</span><select name="phoneCountry" defaultValue="CA"><option value="CA">Canada</option><option value="US">United States</option></select><small>Used only when a phone number is supplied.</small></label></section>
 <section aria-labelledby="company-heading"><h2 id="company-heading">Company <small>optional</small></h2><div className="form-grid"><label className="field"><span>Company name</span><input name="organizationName" autoComplete="organization"/></label><label className="field"><span>Company domain</span><input name="organizationDomain" inputMode="url"/><small>Candidate evidence, not a verified website claim.</small></label></div></section>
 <section aria-labelledby="inquiry-heading"><h2 id="inquiry-heading">Inquiry</h2><label className="field"><span>Subject</span><input name="subject" maxLength={200}/></label><label className="field"><span>Message</span><textarea name="message" rows={5} maxLength={4000}/></label></section>
 <section aria-labelledby="source-heading"><h2 id="source-heading">Source and intake</h2><div className="p1a-readonly"><b>Intake channel</b><span>Manual</span><small>How NexaFlow received this lead.</small></div><div className="form-grid"><label className="field"><span>Source</span><select name="sourceCategory" value={source} onChange={e=>{const next=e.target.value as SourceCategory;setSource(next);if(next!=="social_media")setPlatform("")}}>{sourceCategories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><small>Where the inquiry originated.</small></label><label className="field"><span>Source medium</span><select value={medium} onChange={e=>setMedium(e.target.value as SourceMedium)}><option value="unknown">Unknown</option><option value="organic">Organic</option><option value="paid">Paid</option></select></label></div>{source==="social_media"&&<><label className="field"><span>Social platform</span><select id="sourcePlatform" value={platform} onChange={e=>setPlatform(e.target.value as SocialPlatform|"")} aria-invalid={!!errors.sourcePlatform} aria-describedby={described("sourcePlatform")}><option value="">Choose a platform</option>{socialPlatforms.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><small id="sourcePlatform-help">Required for social media.</small>{errors.sourcePlatform&&<small id="sourcePlatform-error" className="field-error">{errors.sourcePlatform}</small>}</label>{platform==="other_social"&&<label className="field"><span>Platform detail</span><input id="platformDetail" name="platformDetail" maxLength={200} aria-invalid={!!errors.platformDetail}/>{errors.platformDetail&&<small className="field-error">{errors.platformDetail}</small>}</label>}</>}<details><summary>Optional attribution context</summary><div className="form-grid">{["page","account","campaign","ad","form","post"].map(name=><label className="field" key={name}><span>{name[0].toUpperCase()+name.slice(1)}</span><input name={name} maxLength={200}/></label>)}</div></details><p className="helper">Original attribution is preserved. Later corrections are recorded separately.</p></section>
 <div className="row-actions"><button className="primary" disabled={busy}>{busy?"Creating lead…":"Create lead"}</button><Link className="secondary link-button" href="/crm">Cancel</Link></div></form>
}
